export const APP_META = Object.freeze({
  name: "Lift Journal",
  dataSchemaVersion: 2,
  programSchemaVersion: 1,
  programRevision: "2026-08-30",
});

export const DEFAULT_PROFILE = Object.freeze({
  bodyweight: 85,
  age: 34,
  unit: "kg",
});

export const PR_DEFINITIONS = Object.freeze([
  { exerciseId: "snatch", label: "Snatch", initial: 64, target: 70 },
  { exerciseId: "clean_and_jerk", label: "Clean & jerk", initial: 100, target: 105 },
  { exerciseId: "back_squat", label: "Back squat", initial: 150, target: 165 },
  { exerciseId: "front_squat", label: "Front squat", initial: 120, target: 135 },
  { exerciseId: "power_snatch", label: "Power snatch", initial: 50, target: 60, targetLabel: "57–60" },
  { exerciseId: "power_clean", label: "Power clean", initial: 70, target: 85, targetLabel: "80–85" },
  { exerciseId: "snatch_balance", label: "Snatch balance", initial: 70, target: 85, targetLabel: "80–85" },
  { exerciseId: "push_press", label: "Push press", initial: 60, target: 75, targetLabel: "70–75" },
  { exerciseId: "clean", label: "Clean", initial: 100, target: null },
  { exerciseId: "clean_pull", label: "Clean pull / deadlift", initial: 160, target: null },
]);

export const DEFAULT_PRS = Object.freeze(
  Object.fromEntries(PR_DEFINITIONS.map(({ exerciseId, initial }) => [exerciseId, initial])),
);

export const MILESTONES = Object.freeze([
  { stage: 1, snatch: 70, cleanAndJerk: 105, total: 175 },
  { stage: 2, snatch: 80, cleanAndJerk: 115, total: 195 },
  { stage: 3, snatch: 90, cleanAndJerk: 125, total: 215 },
  { stage: 4, snatch: 100, cleanAndJerk: 135, total: 235 },
]);

// The video IDs below are kept in data rather than UI code so a video can be
// replaced without touching the workout or library rendering logic.
export const EXERCISES = Object.freeze([
  {
    id: "snatch",
    name: "Snatch",
    category: "Snatch",
    purpose: "Build the competition lift and a confident, stable receiving position.",
    cues: ["Push through the whole foot", "Stay close, then pull under", "Punch up and own the bottom"],
    videoId: "1Lv1IyigIUY",
    sourceUrl: "https://www.catalystathletics.com/exercise/58/Snatch/",
    tracksOutcome: true,
  },
  {
    id: "power_snatch",
    name: "Power snatch",
    category: "Snatch",
    purpose: "Develop explosive extension, a fast turnover and precise high receiving mechanics.",
    cues: ["Finish the leg drive", "Meet the bar actively", "Receive upright above parallel"],
    videoId: "ydHHsju1-Nc",
    sourceUrl: "https://www.catalystathletics.com/exercise/61/Power-Snatch/",
    tracksOutcome: true,
  },
  {
    id: "snatch_pull",
    name: "Snatch pull",
    category: "Snatch",
    purpose: "Strengthen snatch positions and vertical acceleration with more load than the full lift.",
    cues: ["Keep the bar close", "Hold the back angle past the knee", "Extend vertically with speed"],
    videoId: "G1QygZ3Kd3w",
    sourceUrl: "https://www.catalystathletics.com/exercise/97/Snatch-Pull/",
    tracksOutcome: false,
  },
  {
    id: "snatch_balance",
    name: "Snatch balance",
    category: "Overhead",
    purpose: "Train speed under the bar, receiving strength and confidence in the snatch bottom.",
    cues: ["Dip smoothly and vertically", "Move down; do not launch the bar", "Punch and stabilize immediately"],
    videoId: "O2anVg-_tLQ",
    sourceUrl: "https://www.catalystathletics.com/video/1577/Snatch-Balance-Variations/",
    tracksOutcome: true,
  },
  {
    id: "overhead_squat",
    name: "Overhead squat",
    category: "Overhead",
    purpose: "Build mobility, balance and strength in the snatch receiving position.",
    cues: ["Set the upper back", "Stay balanced over the whole foot", "Push up into the bar"],
    videoId: "2Nntfq9mDfg",
    sourceUrl: "https://www.catalystathletics.com/exercise/79/Overhead-Squat/",
    tracksOutcome: false,
  },
  {
    id: "clean",
    name: "Clean",
    category: "Clean",
    purpose: "Develop the competition clean from the floor through a strong rack and recovery.",
    cues: ["Push from the floor", "Keep the bar close", "Turn over fast and drive out of the bottom"],
    videoId: "oQIaWLrB318",
    sourceUrl: "https://www.catalystathletics.com/exercise/59/Clean/",
    tracksOutcome: true,
  },
  {
    id: "pause_clean",
    name: "Pause clean",
    category: "Clean",
    purpose: "Reinforce balance and exact pulling positions before a fast finish and turnover.",
    cues: ["Pause without losing tension", "Stay balanced over the whole foot", "Accelerate after the pause"],
    videoId: "oQIaWLrB318",
    sourceUrl: "https://www.catalystathletics.com/exercise/323/Clean-Segment-Clean/",
    tracksOutcome: true,
  },
  {
    id: "power_clean",
    name: "Power clean",
    category: "Clean",
    purpose: "Build specific power, a complete extension and an active high rack.",
    cues: ["Finish with the legs", "Pull under instead of curling", "Meet the bar with an upright trunk"],
    videoId: "YG8M_-11C2A",
    sourceUrl: "https://www.catalystathletics.com/exercise/67/Power-Clean/",
    tracksOutcome: true,
  },
  {
    id: "clean_pull",
    name: "Clean pull",
    category: "Clean",
    purpose: "Build clean-specific pulling strength while preserving balance, posture and speed.",
    cues: ["Push the floor away", "Keep the bar against the body", "Extend vertically; finish tall"],
    videoId: "xx8WkFrST2Y",
    sourceUrl: "https://www.catalystathletics.com/exercise/98/Clean-Pull/",
    tracksOutcome: false,
  },
  {
    id: "clean_and_jerk",
    name: "Clean & jerk",
    category: "Competition",
    purpose: "Practice the complete competition lift with a decisive, legal overhead lockout.",
    cues: ["Make the clean precise", "Reset before the jerk", "Punch to immediate lockout and hold"],
    videoId: "bNCXgyosXlc",
    sourceUrl: "https://www.catalystathletics.com/exercise/76/Clean-Jerk/",
    tracksOutcome: true,
  },
  {
    id: "jerk",
    name: "Jerk",
    category: "Jerk",
    purpose: "Develop an efficient drive, fast split and unmistakable overhead fixation.",
    cues: ["Dip straight and stay connected", "Drive through the bar", "Punch fast, lock immediately, then recover"],
    videoId: "2GPA-cjUFnA",
    sourceUrl: "https://www.catalystathletics.com/exercise/60/Split-Jerk/",
    tracksOutcome: true,
  },
  {
    id: "push_press",
    name: "Push press",
    category: "Jerk",
    purpose: "Build overhead strength while rehearsing the dip, drive and arm timing of the jerk.",
    cues: ["Dip vertically", "Finish the leg drive", "Press up and slightly back to a hard lockout"],
    videoId: "dhZlP5NX-wo",
    sourceUrl: "https://www.catalystathletics.com/exercise/87/Push-Press/",
    tracksOutcome: false,
  },
  {
    id: "back_squat",
    name: "Back squat",
    category: "Strength",
    purpose: "Develop general leg and trunk strength for both competition lifts.",
    cues: ["Brace before descending", "Keep whole-foot balance", "Drive up without losing posture"],
    videoId: "Akd5xmZlsvg",
    sourceUrl: "https://www.catalystathletics.com/exercise/77/Back-Squat/",
    tracksOutcome: false,
  },
  {
    id: "front_squat",
    name: "Front squat",
    category: "Strength",
    purpose: "Build clean recovery strength, upright posture and jerk-specific leg strength.",
    cues: ["Lift the elbows", "Brace and stay upright", "Drive straight out of the bottom"],
    videoId: "lNJ3DyibYZQ",
    sourceUrl: "https://www.catalystathletics.com/exercise/78/Front-Squat/",
    tracksOutcome: false,
  },
  {
    id: "upper_back",
    name: "Rows / pull-ups",
    category: "Accessory",
    purpose: "Support upper-back strength and bar control.",
    cues: ["Use a full range", "Keep the trunk controlled", "Stop before technique changes"],
    videoId: null,
    sourceUrl: null,
    tracksOutcome: false,
  },
  {
    id: "trunk",
    name: "Trunk work",
    category: "Accessory",
    purpose: "Build bracing capacity that transfers to pulls, squats and overhead positions.",
    cues: ["Choose one focused movement", "Brace without holding your breath too long", "Keep reps controlled"],
    videoId: null,
    sourceUrl: null,
    tracksOutcome: false,
  },
  {
    id: "triceps_upper_back",
    name: "Triceps / upper back",
    category: "Accessory",
    purpose: "Support jerk lockout strength and upper-back position.",
    cues: ["Use controlled reps", "Choose pain-free movements", "Leave a little in reserve"],
    videoId: null,
    sourceUrl: null,
    tracksOutcome: false,
  },
  {
    id: "posterior_chain",
    name: "Posterior chain",
    category: "Accessory",
    purpose: "Add optional hamstring, glute and back strength without compromising recovery.",
    cues: ["Choose a familiar hinge", "Keep the back set", "Skip it if recovery is poor"],
    videoId: null,
    sourceUrl: null,
    tracksOutcome: false,
  },
]);

export const EXERCISE_BY_ID = Object.freeze(
  Object.fromEntries(EXERCISES.map((exercise) => [exercise.id, exercise])),
);

export const PROGRAM_DEFINITION = Object.freeze({
  schemaVersion: 1,
  id: "stability-power-base-v1",
  revision: APP_META.programRevision,
  name: "Stability & Power Base",
  reviewWindow: "8–12 weeks",
  priorities: [
    "Snatch technique and receiving stability",
    "Overhead strength and stability",
    "Competition-quality jerk lockout",
    "Specific power in the power snatch and power clean",
    "Gradual squat development",
  ],
  loadingRules: [
    "Keep technical lifts crisp and stop adding weight when positions or timing deteriorate.",
    "Keep squats at 1–3 reps in reserve in most sessions.",
    "Add 2.5 kg when every prescribed set is strong and recovery is good.",
    "Plan near-max attempts instead of taking them every session.",
    "Tuesday, Thursday and Sunday are recovery days; easy cycling, walking or mobility is fine if it does not impair lifting.",
  ],
  reviewCriteria: [
    "More stable 60–65 kg snatches",
    "Progress toward a 70 kg snatch",
    "Snatch balance around 80 kg",
    "Improved power-clean and power-snatch numbers",
    "Repeatable, technically legal 85–95 kg clean & jerks",
  ],
  days: [
    {
      id: "monday",
      weekday: 1,
      name: "Monday",
      title: "Snatch + Back Squat",
      focus: "Receiving stability and foundational leg strength",
      exercises: [
        {
          exerciseId: "snatch",
          sets: { min: 5, max: 8, default: 6 },
          reps: "1–2",
          defaultReps: 1,
          recommendation: "70–85% · 45–55 kg",
          initialWeight: 45,
          progression: { step: 2.5, maxWeight: 55 },
          notes: "Pause for 2 seconds in the receiving position on technical reps.",
          priority: 1,
          videoRef: "snatch",
        },
        {
          exerciseId: "snatch_pull",
          sets: 4,
          reps: "3",
          defaultReps: 3,
          recommendation: "90–105% of snatch · 58–67 kg",
          initialWeight: 58,
          progression: { step: 2.5, maxWeight: 67 },
          notes: "Maintain snatch positions and speed.",
          priority: 2,
          videoRef: "snatch_pull",
        },
        {
          exerciseId: "back_squat",
          sets: 4,
          reps: "4",
          defaultReps: 4,
          recommendation: "72–80% · 107.5–120 kg",
          initialWeight: 107.5,
          progression: { step: 2.5, maxWeight: 120 },
          notes: "Leave 1–3 reps in reserve.",
          priority: 3,
          videoRef: "back_squat",
        },
        {
          exerciseId: "upper_back",
          sets: { min: 3, max: 4, default: 3 },
          reps: "6–10",
          defaultReps: 8,
          recommendation: "Controlled, submaximal",
          initialWeight: "",
          notes: "Choose rows or pull-ups.",
          priority: 4,
          videoRef: null,
        },
        {
          exerciseId: "trunk",
          sets: 3,
          reps: "Controlled",
          defaultReps: 10,
          recommendation: "Moderate",
          initialWeight: "",
          notes: "Choose one trunk exercise and keep the quality high.",
          priority: 5,
          videoRef: null,
        },
      ],
    },
    {
      id: "wednesday",
      weekday: 3,
      name: "Wednesday",
      title: "Clean & Jerk + Front Squat",
      focus: "Decisive jerk lockout and clean-specific leg strength",
      exercises: [
        {
          exerciseId: "clean_and_jerk",
          sets: { min: 5, max: 7, default: 6 },
          reps: "1",
          defaultReps: 1,
          recommendation: "75–88% · 75–88 kg",
          initialWeight: 75,
          progression: { step: 2.5, maxWeight: 88 },
          notes: "Create immediate, unmistakable elbow lockout and hold it.",
          priority: 1,
          videoRef: "clean_and_jerk",
        },
        {
          exerciseId: "pause_clean",
          sets: { min: 3, max: 4, default: 3 },
          reps: "1–2",
          defaultReps: 2,
          recommendation: "Moderate",
          initialWeight: 65,
          progression: { step: 2.5, maxWeight: null },
          notes: "Use a pause clean or a clean + front squat complex.",
          priority: 2,
          videoRef: "clean",
        },
        {
          exerciseId: "front_squat",
          sets: 4,
          reps: "3",
          defaultReps: 3,
          recommendation: "87.5–97.5 kg",
          initialWeight: 87.5,
          progression: { step: 2.5, maxWeight: 97.5 },
          notes: "Stay upright; leave 1–3 reps in reserve.",
          priority: 3,
          videoRef: "front_squat",
        },
        {
          exerciseId: "push_press",
          sets: 4,
          reps: "4",
          defaultReps: 4,
          recommendation: "Build gradually toward 70–75 kg",
          initialWeight: 45,
          progression: { step: 2.5, maxWeight: 75 },
          notes: "Drive vertically and finish every rep with a hard lockout.",
          priority: 4,
          videoRef: "push_press",
        },
        {
          exerciseId: "triceps_upper_back",
          sets: 3,
          reps: "8–12",
          defaultReps: 10,
          recommendation: "Controlled, submaximal",
          initialWeight: "",
          notes: "Select one triceps or upper-back accessory.",
          priority: 5,
          videoRef: null,
        },
      ],
    },
    {
      id: "friday",
      weekday: 5,
      name: "Friday",
      title: "Power + Overhead Stability",
      focus: "Specific power and a stable overhead receiving position",
      exercises: [
        {
          exerciseId: "power_snatch",
          sets: 5,
          reps: "2",
          defaultReps: 2,
          recommendation: "35–40 kg",
          initialWeight: 35,
          progression: { step: 2.5, maxWeight: 40 },
          notes: "Receive tall and connected; do not chase borderline depth.",
          priority: 1,
          videoRef: "power_snatch",
        },
        {
          exerciseId: "snatch_balance",
          sets: 4,
          reps: "2",
          defaultReps: 2,
          recommendation: "50–60 kg",
          initialWeight: 50,
          progression: { step: 2.5, maxWeight: 60 },
          notes: "Emphasize speed under the bar and a stable bottom position.",
          priority: 2,
          videoRef: "snatch_balance",
        },
        {
          exerciseId: "overhead_squat",
          sets: 3,
          reps: "3",
          defaultReps: 3,
          recommendation: "Moderate",
          initialWeight: 40,
          progression: { step: 2.5, maxWeight: null },
          notes: "Pause for 3 seconds in the bottom of every rep.",
          priority: 3,
          videoRef: "overhead_squat",
        },
        {
          exerciseId: "power_clean",
          sets: 5,
          reps: "2",
          defaultReps: 2,
          recommendation: "50–55 kg",
          initialWeight: 50,
          progression: { step: 2.5, maxWeight: 55 },
          notes: "Re-establish whether the 70 kg PR is current with crisp lifts.",
          priority: 4,
          videoRef: "power_clean",
        },
        {
          exerciseId: "posterior_chain",
          sets: 3,
          reps: "5–8",
          defaultReps: 6,
          recommendation: "Optional · moderate",
          initialWeight: "",
          notes: "Skip this if it would interfere with Saturday's coached session.",
          priority: 5,
          videoRef: null,
          optional: true,
        },
      ],
    },
    {
      id: "saturday",
      weekday: 6,
      name: "Saturday",
      title: "Alfa Omega Coached Session",
      focus: "Competition lifts, coach feedback and repeatable execution",
      exercises: [
        {
          exerciseId: "snatch",
          sets: { min: 1, max: 10, default: 5 },
          reps: "Coach determines",
          defaultReps: 1,
          recommendation: "Coach determines intensity",
          initialWeight: "",
          notes: "Focus on receiving position, stability and repeatability.",
          priority: 1,
          videoRef: "snatch",
        },
        {
          exerciseId: "clean_and_jerk",
          sets: { min: 1, max: 10, default: 5 },
          reps: "Coach determines",
          defaultReps: 1,
          recommendation: "Coach determines intensity",
          initialWeight: "",
          notes: "Focus on a legal, decisive jerk lockout.",
          priority: 2,
          videoRef: "clean_and_jerk",
        },
      ],
      sessionPrompt: "Record only 1–2 actionable cues from coach Tim. Keep athlete observations and coach cues separate.",
    },
  ],
});

export const CHART_EXERCISE_IDS = Object.freeze([
  "snatch",
  "clean_and_jerk",
  "back_squat",
  "front_squat",
  "power_snatch",
  "power_clean",
]);

export function getExercise(exerciseId) {
  return EXERCISE_BY_ID[exerciseId] ?? {
    id: exerciseId,
    name: "Unknown exercise",
    category: "Other",
    purpose: "Imported exercise",
    cues: [],
    videoId: null,
    sourceUrl: null,
    tracksOutcome: false,
  };
}

export function getProgramDay(dayId) {
  return PROGRAM_DEFINITION.days.find((day) => day.id === dayId) ?? null;
}
