import { APP_META, EXERCISE_BY_ID } from "./public-data.js";
export { APP_META, EXERCISES, EXERCISE_BY_ID } from "./public-data.js";

// Personal defaults belong only to the original single-athlete app.
export const DEFAULT_PROFILE = Object.freeze({
  bodyweight: 85,
  age: 34,
  unit: "kg",
});

export const PR_DEFINITIONS = Object.freeze([
  { exerciseId: "snatch", label: "Snatch", initial: 64, target: 70 },
  { exerciseId: "clean_and_jerk", label: "Clean & jerk", initial: 100, target: 105 },
  { exerciseId: "back_squat", label: "Back squat", initial: 150, target: 165 },
  { exerciseId: "front_squat", label: "Front squat", initial: 120, target: 135 },
  { exerciseId: "power_snatch", label: "Power snatch", initial: 50, target: 60, targetLabel: "57–60" },
  { exerciseId: "power_clean", label: "Power clean", initial: 70, target: 85, targetLabel: "80–85" },
  { exerciseId: "snatch_balance", label: "Snatch balance", initial: 70, target: 85, targetLabel: "80–85" },
  { exerciseId: "push_press", label: "Push press", initial: 60, target: 75, targetLabel: "70–75" },
  { exerciseId: "clean", label: "Clean", initial: 100, target: null },
  { exerciseId: "clean_pull", label: "Clean pull / deadlift", initial: 160, target: null },
]);

export const DEFAULT_PRS = Object.freeze(
  Object.fromEntries(PR_DEFINITIONS.map(({ exerciseId, initial }) => [exerciseId, initial])),
);

export const MILESTONES = Object.freeze([
  { stage: 1, snatch: 70, cleanAndJerk: 105, total: 175 },
  { stage: 2, snatch: 80, cleanAndJerk: 115, total: 195 },
  { stage: 3, snatch: 90, cleanAndJerk: 125, total: 215 },
  { stage: 4, snatch: 100, cleanAndJerk: 135, total: 235 },
]);

export const PROGRAM_DEFINITION = Object.freeze({
  schemaVersion: 1,
  id: "stability-power-base-v1",
  revision: APP_META.programRevision,
  name: "Stability & Power Base",
  reviewWindow: "8–12 weeks",
  priorities: [
    "Snatch technique and receiving stability",
    "Overhead strength and stability",
    "Competition-quality jerk lockout",
    "Specific power in the power snatch and power clean",
    "Gradual squat development",
  ],
  loadingRules: [
    "Keep technical lifts crisp and stop adding weight when positions or timing deteriorate.",
    "Keep squats at 1–3 reps in reserve in most sessions.",
    "Add 2 kg total (1 kg per side) after all prescribed work is completed successfully. Automatic targets use whole kilograms. Misses, high RPE or limited recovery hold the load.",
    "Plan near-max attempts instead of taking them every session.",
    "Tuesday, Thursday and Sunday are recovery days; easy cycling, walking or mobility is fine if it does not impair lifting.",
  ],
  reviewCriteria: [
    "More stable 60–65 kg snatches",
    "Progress toward a 70 kg snatch",
    "Snatch balance around 80 kg",
    "Improved power-clean and power-snatch numbers",
    "Repeatable, technically legal 85–95 kg clean & jerks",
  ],
  days: [
    {
      id: "gym_accessories",
      weekday: null,
      name: "Any day",
      title: "Gym Accessories",
      focus: "Normal gym · rack, barbell and floor space · no platform or dropped lifts",
      sessionPrompt: "Warm up first and choose familiar, comfortable loads with 2–3 reps in reserve. Rest about 2 minutes between sets. Use rack safeties, lower every rep under control and follow the gym’s rules. This is an alternative session, not extra work you must add to the full week. Log total bar weight including the bar; for bodyweight movements enter 0 kg.",
      exercises: [
        { exerciseId: "romanian_deadlift", sets: 3, reps: "8", defaultReps: 8, initialWeight: "", progression: { step: 2 },
          recommendation: "Choose a comfortable starting weight", notes: "Start and finish from the rack. Keep the bar close, lower under control and do not drop it. Record total bar weight.", priority: 1, videoRef: "romanian_deadlift" },
        { exerciseId: "strict_press", sets: 3, reps: "8", defaultReps: 8, initialWeight: "", progression: { step: 2 },
          recommendation: "Choose a comfortable starting weight", notes: "Press from the rack without leg drive. Use a lighter bar if needed and leave 2–3 reps in reserve. No jerks or dropped bars.", priority: 2, videoRef: "strict_press" },
        { exerciseId: "barbell_row", sets: 3, reps: "10", defaultReps: 10, initialWeight: "", progression: { step: 2 },
          recommendation: "Choose a comfortable starting weight", notes: "Start from the rack, hinge to row and avoid heaving. Lower every rep under control. Record total bar weight.", priority: 3, videoRef: "barbell_row" },
        { exerciseId: "split_squat", sets: 3, reps: "16 total · 8 per leg", defaultReps: 16, initialWeight: "", progression: { step: 2 },
          recommendation: "Bodyweight or a comfortable added load", notes: "One logged set is 8 reps per leg: enter 16 total reps. Enter 0 kg for bodyweight, otherwise total added weight. Use rack safeties with a barbell; bodyweight sessions stay at 0 until you choose a loaded baseline.", priority: 4, videoRef: "split_squat" },
        { exerciseId: "dead_bug", sets: 3, reps: "16 total · 8 per side", defaultReps: 16, initialWeight: 0,
          recommendation: "Bodyweight · 0 kg", notes: "Alternate sides slowly. One logged set is 8 per side: enter 16 total reps and 0 kg. No automatic weight increases.", priority: 5, videoRef: "dead_bug" },
      ],
    },
    {
      id: "monday",
      weekday: 1,
      name: "Monday",
      title: "Snatch + Back Squat",
      focus: "Receiving stability and foundational leg strength",
      exercises: [
        {
          exerciseId: "snatch",
          sets: { min: 5, max: 8, default: 6 },
          reps: "1–2",
          defaultReps: 1,
          recommendation: "70–85% · 45–55 kg",
          initialWeight: 45,
          progression: { step: 2 },
          notes: "Pause for 2 seconds in the receiving position on technical reps.",
          priority: 1,
          videoRef: "snatch",
        },
        {
          exerciseId: "snatch_pull",
          sets: 4,
          reps: "3",
          defaultReps: 3,
          recommendation: "90–105% of snatch · 58–67 kg",
          initialWeight: 58,
          progression: { step: 2 },
          notes: "Maintain snatch positions and speed.",
          priority: 2,
          videoRef: "snatch_pull",
        },
        {
          exerciseId: "back_squat",
          sets: 4,
          reps: "4",
          defaultReps: 4,
          recommendation: "72–80% · 107–120 kg",
          initialWeight: 107,
          progression: { step: 2 },
          notes: "Leave 1–3 reps in reserve.",
          priority: 3,
          videoRef: "back_squat",
        },
        {
          exerciseId: "upper_back",
          sets: { min: 3, max: 4, default: 3 },
          reps: "6–10",
          defaultReps: 8,
          recommendation: "Controlled, submaximal",
          initialWeight: "",
          notes: "Choose rows or pull-ups.",
          priority: 4,
          videoRef: null,
        },
        {
          exerciseId: "trunk",
          sets: 3,
          reps: "Controlled",
          defaultReps: 10,
          recommendation: "Moderate",
          initialWeight: "",
          notes: "Choose one trunk exercise and keep the quality high.",
          priority: 5,
          videoRef: null,
        },
      ],
    },
    {
      id: "wednesday",
      weekday: 3,
      name: "Wednesday",
      title: "Clean & Jerk + Front Squat",
      focus: "Decisive jerk lockout and clean-specific leg strength",
      exercises: [
        {
          exerciseId: "clean_and_jerk",
          sets: { min: 5, max: 7, default: 6 },
          reps: "1",
          defaultReps: 1,
          recommendation: "75–88% · 75–88 kg",
          initialWeight: 75,
          progression: { step: 2 },
          notes: "Create immediate, unmistakable elbow lockout and hold it.",
          priority: 1,
          videoRef: "clean_and_jerk",
        },
        {
          exerciseId: "pause_clean",
          sets: { min: 3, max: 4, default: 3 },
          reps: "1–2",
          defaultReps: 2,
          recommendation: "Moderate",
          initialWeight: 65,
          progression: { step: 2 },
          notes: "Use a pause clean or a clean + front squat complex.",
          priority: 2,
          videoRef: "clean",
        },
        {
          exerciseId: "front_squat",
          sets: 4,
          reps: "3",
          defaultReps: 3,
          recommendation: "87–97 kg",
          initialWeight: 87,
          progression: { step: 2 },
          notes: "Stay upright; leave 1–3 reps in reserve.",
          priority: 3,
          videoRef: "front_squat",
        },
        {
          exerciseId: "push_press",
          sets: 4,
          reps: "4",
          defaultReps: 4,
          recommendation: "Build gradually toward 70–75 kg",
          initialWeight: 45,
          progression: { step: 2 },
          notes: "Drive vertically and finish every rep with a hard lockout.",
          priority: 4,
          videoRef: "push_press",
        },
        {
          exerciseId: "triceps_upper_back",
          sets: 3,
          reps: "8–12",
          defaultReps: 10,
          recommendation: "Controlled, submaximal",
          initialWeight: "",
          notes: "Select one triceps or upper-back accessory.",
          priority: 5,
          videoRef: null,
        },
      ],
    },
    {
      id: "friday",
      weekday: 5,
      name: "Friday",
      title: "Power + Overhead Stability",
      focus: "Specific power and a stable overhead receiving position",
      exercises: [
        {
          exerciseId: "power_snatch",
          sets: 5,
          reps: "2",
          defaultReps: 2,
          recommendation: "35–40 kg",
          initialWeight: 35,
          progression: { step: 2 },
          notes: "Receive tall and connected; do not chase borderline depth.",
          priority: 1,
          videoRef: "power_snatch",
        },
        {
          exerciseId: "snatch_balance",
          sets: 4,
          reps: "2",
          defaultReps: 2,
          recommendation: "50–60 kg",
          initialWeight: 50,
          progression: { step: 2 },
          notes: "Emphasize speed under the bar and a stable bottom position.",
          priority: 2,
          videoRef: "snatch_balance",
        },
        {
          exerciseId: "overhead_squat",
          sets: 3,
          reps: "3",
          defaultReps: 3,
          recommendation: "Moderate",
          initialWeight: 40,
          progression: { step: 2 },
          notes: "Pause for 3 seconds in the bottom of every rep.",
          priority: 3,
          videoRef: "overhead_squat",
        },
        {
          exerciseId: "power_clean",
          sets: 5,
          reps: "2",
          defaultReps: 2,
          recommendation: "50–55 kg",
          initialWeight: 50,
          progression: { step: 2 },
          notes: "Re-establish whether the 70 kg PR is current with crisp lifts.",
          priority: 4,
          videoRef: "power_clean",
        },
        {
          exerciseId: "posterior_chain",
          sets: 3,
          reps: "5–8",
          defaultReps: 6,
          recommendation: "Optional · moderate",
          initialWeight: "",
          notes: "Skip this if it would interfere with Saturday's coached session.",
          priority: 5,
          videoRef: null,
          optional: true,
        },
      ],
    },
    {
      id: "saturday",
      weekday: 6,
      name: "Saturday",
      title: "Alfa Omega Coached Session",
      focus: "Competition lifts, coach feedback and repeatable execution",
      exercises: [
        {
          exerciseId: "snatch",
          sets: { min: 1, max: 10, default: 5 },
          reps: "Coach determines",
          defaultReps: 1,
          recommendation: "Coach determines intensity",
          initialWeight: "",
          notes: "Focus on receiving position, stability and repeatability.",
          priority: 1,
          videoRef: "snatch",
        },
        {
          exerciseId: "clean_and_jerk",
          sets: { min: 1, max: 10, default: 5 },
          reps: "Coach determines",
          defaultReps: 1,
          recommendation: "Coach determines intensity",
          initialWeight: "",
          notes: "Focus on a legal, decisive jerk lockout.",
          priority: 2,
          videoRef: "clean_and_jerk",
        },
      ],
      sessionPrompt: "Record only 1–2 actionable cues from coach Tim. Keep athlete observations and coach cues separate.",
    },
  ],
});

export const CHART_EXERCISE_IDS = Object.freeze([
  "snatch",
  "clean_and_jerk",
  "back_squat",
  "front_squat",
  "power_snatch",
  "power_clean",
]);

export function getExercise(exerciseId) {
  return EXERCISE_BY_ID[exerciseId] ?? {
    id: exerciseId,
    name: "Unknown exercise",
    category: "Other",
    purpose: "Imported exercise",
    cues: [],
    videoId: null,
    sourceUrl: null,
    tracksOutcome: false,
  };
}

export function getProgramDay(dayId) {
  return PROGRAM_DEFINITION.days.find((day) => day.id === dayId) ?? null;
}
