// Shared programme and exercise catalogue. No athlete profile or personal records.
export const APP_META = Object.freeze({
  name: "Lift Journal",
  dataSchemaVersion: 2,
  programSchemaVersion: 1,
  programRevision: "2026-09-05",
});

// The video IDs below are kept in data rather than UI code so a video can be
// replaced without touching the workout or library rendering logic.
export const EXERCISES = Object.freeze([
  {
    id: "snatch",
    name: "Snatch",
    category: "Snatch",
    purpose: "Build the competition lift and a confident, stable receiving position.",
    cues: ["Push through the whole foot", "Stay close, then pull under", "Punch up and own the bottom"],
    videoId: "1Lv1IyigIUY",
    sourceUrl: "https://www.catalystathletics.com/exercise/58/Snatch/",
    tracksOutcome: true,
  },
  {
    id: "power_snatch",
    name: "Power snatch",
    category: "Snatch",
    purpose: "Develop explosive extension, a fast turnover and precise high receiving mechanics.",
    cues: ["Finish the leg drive", "Meet the bar actively", "Receive upright above parallel"],
    videoId: "ydHHsju1-Nc",
    sourceUrl: "https://www.catalystathletics.com/exercise/61/Power-Snatch/",
    tracksOutcome: true,
  },
  {
    id: "snatch_pull",
    name: "Snatch pull",
    category: "Snatch",
    purpose: "Strengthen snatch positions and vertical acceleration with more load than the full lift.",
    cues: ["Keep the bar close", "Hold the back angle past the knee", "Extend vertically with speed"],
    videoId: "G1QygZ3Kd3w",
    sourceUrl: "https://www.catalystathletics.com/exercise/97/Snatch-Pull/",
    tracksOutcome: false,
  },
  {
    id: "snatch_balance",
    name: "Snatch balance",
    category: "Overhead",
    purpose: "Train speed under the bar, receiving strength and confidence in the snatch bottom.",
    cues: ["Dip smoothly and vertically", "Move down; do not launch the bar", "Punch and stabilize immediately"],
    videoId: "O2anVg-_tLQ",
    sourceUrl: "https://www.catalystathletics.com/video/1577/Snatch-Balance-Variations/",
    tracksOutcome: true,
  },
  {
    id: "overhead_squat",
    name: "Overhead squat",
    category: "Overhead",
    purpose: "Build mobility, balance and strength in the snatch receiving position.",
    cues: ["Set the upper back", "Stay balanced over the whole foot", "Push up into the bar"],
    videoId: "2Nntfq9mDfg",
    sourceUrl: "https://www.catalystathletics.com/exercise/79/Overhead-Squat/",
    tracksOutcome: false,
  },
  {
    id: "clean",
    name: "Clean",
    category: "Clean",
    purpose: "Develop the competition clean from the floor through a strong rack and recovery.",
    cues: ["Push from the floor", "Keep the bar close", "Turn over fast and drive out of the bottom"],
    videoId: "oQIaWLrB318",
    sourceUrl: "https://www.catalystathletics.com/exercise/59/Clean/",
    tracksOutcome: true,
  },
  {
    id: "pause_clean",
    name: "Pause clean",
    category: "Clean",
    purpose: "Reinforce balance and exact pulling positions before a fast finish and turnover.",
    cues: ["Pause without losing tension", "Stay balanced over the whole foot", "Accelerate after the pause"],
    videoId: "oQIaWLrB318",
    sourceUrl: "https://www.catalystathletics.com/exercise/323/Clean-Segment-Clean/",
    tracksOutcome: true,
  },
  {
    id: "power_clean",
    name: "Power clean",
    category: "Clean",
    purpose: "Build specific power, a complete extension and an active high rack.",
    cues: ["Finish with the legs", "Pull under instead of curling", "Meet the bar with an upright trunk"],
    videoId: "YG8M_-11C2A",
    sourceUrl: "https://www.catalystathletics.com/exercise/67/Power-Clean/",
    tracksOutcome: true,
  },
  {
    id: "clean_pull",
    name: "Clean pull",
    category: "Clean",
    purpose: "Build clean-specific pulling strength while preserving balance, posture and speed.",
    cues: ["Push the floor away", "Keep the bar against the body", "Extend vertically; finish tall"],
    videoId: "xx8WkFrST2Y",
    sourceUrl: "https://www.catalystathletics.com/exercise/98/Clean-Pull/",
    tracksOutcome: false,
  },
  {
    id: "clean_and_jerk",
    name: "Clean & jerk",
    category: "Competition",
    purpose: "Practice the complete competition lift with a decisive, legal overhead lockout.",
    cues: ["Make the clean precise", "Reset before the jerk", "Punch to immediate lockout and hold"],
    videoId: "bNCXgyosXlc",
    sourceUrl: "https://www.catalystathletics.com/exercise/76/Clean-Jerk/",
    tracksOutcome: true,
  },
  {
    id: "jerk",
    name: "Jerk",
    category: "Jerk",
    purpose: "Develop an efficient drive, fast split and unmistakable overhead fixation.",
    cues: ["Dip straight and stay connected", "Drive through the bar", "Punch fast, lock immediately, then recover"],
    videoId: "2GPA-cjUFnA",
    sourceUrl: "https://www.catalystathletics.com/exercise/60/Split-Jerk/",
    tracksOutcome: true,
  },
  {
    id: "push_press",
    name: "Push press",
    category: "Jerk",
    purpose: "Build overhead strength while rehearsing the dip, drive and arm timing of the jerk.",
    cues: ["Dip vertically", "Finish the leg drive", "Press up and slightly back to a hard lockout"],
    videoId: "dhZlP5NX-wo",
    sourceUrl: "https://www.catalystathletics.com/exercise/87/Push-Press/",
    tracksOutcome: false,
  },
  {
    id: "back_squat",
    name: "Back squat",
    category: "Strength",
    purpose: "Develop general leg and trunk strength for both competition lifts.",
    cues: ["Brace before descending", "Keep whole-foot balance", "Drive up without losing posture"],
    videoId: "Akd5xmZlsvg",
    sourceUrl: "https://www.catalystathletics.com/exercise/77/Back-Squat/",
    tracksOutcome: false,
  },
  {
    id: "front_squat",
    name: "Front squat",
    category: "Strength",
    purpose: "Build clean recovery strength, upright posture and jerk-specific leg strength.",
    cues: ["Lift the elbows", "Brace and stay upright", "Drive straight out of the bottom"],
    videoId: "lNJ3DyibYZQ",
    sourceUrl: "https://www.catalystathletics.com/exercise/78/Front-Squat/",
    tracksOutcome: false,
  },
  {
    id: "upper_back",
    name: "Rows / pull-ups",
    category: "Accessory",
    purpose: "Support upper-back strength and bar control.",
    cues: ["Use a full range", "Keep the trunk controlled", "Stop before technique changes"],
    videoId: null,
    sourceUrl: null,
    tracksOutcome: false,
  },
  {
    id: "trunk",
    name: "Trunk work",
    category: "Accessory",
    purpose: "Build bracing capacity that transfers to pulls, squats and overhead positions.",
    cues: ["Choose one focused movement", "Brace without holding your breath too long", "Keep reps controlled"],
    videoId: null,
    sourceUrl: null,
    tracksOutcome: false,
  },
  {
    id: "triceps_upper_back",
    name: "Triceps / upper back",
    category: "Accessory",
    purpose: "Support jerk lockout strength and upper-back position.",
    cues: ["Use controlled reps", "Choose pain-free movements", "Leave a little in reserve"],
    videoId: null,
    sourceUrl: null,
    tracksOutcome: false,
  },
  {
    id: "posterior_chain",
    name: "Posterior chain",
    category: "Accessory",
    purpose: "Add optional hamstring, glute and back strength without compromising recovery.",
    cues: ["Choose a familiar hinge", "Keep the back set", "Skip it if recovery is poor"],
    videoId: null,
    sourceUrl: null,
    tracksOutcome: false,
  },
  {
    id: "romanian_deadlift", name: "Romanian deadlift", category: "Accessory",
    purpose: "Train the hamstrings and glutes with a controlled barbell hinge.",
    cues: ["Unrack the bar and brace", "Push the hips back with soft knees", "Keep the bar close; lower only as far as your position allows", "Return the bar to the rack without dropping it"],
    videoId: "_U9KjljQyd0",
    sourceUrl: "https://www.catalystathletics.com/exercise/101/Romanian-Deadlift-RDL/",
    tracksOutcome: false,
  },
  {
    id: "strict_press", name: "Strict press", category: "Accessory",
    purpose: "Build overhead strength with a controlled press from the rack.",
    cues: ["Brace and keep the ribs down", "Press without a leg drive", "Lower to the shoulders under control and re-rack"],
    videoId: "_cfNP_VXs_U",
    sourceUrl: "https://www.catalystathletics.com/exercise/90/Press/",
    tracksOutcome: false,
  },
  {
    id: "barbell_row", name: "Barbell row", category: "Accessory",
    purpose: "Build upper-back strength using a controlled pulling movement.",
    cues: ["Set the bar in the rack to start", "Hinge and keep your torso steady", "Pull toward the lower ribs without jerking", "Lower under control"],
    videoId: "D4eruYL5_Fc",
    sourceUrl: "https://www.catalystathletics.com/exercise/171/Bent-Row/",
    tracksOutcome: false,
  },
  {
    id: "split_squat", name: "Split squat", category: "Accessory",
    purpose: "Train single-leg strength and control from a stable split stance.",
    cues: ["Start with bodyweight if needed", "Keep the front foot planted", "Use the rack safeties if loading a barbell", "Complete both legs before logging the set"],
    videoId: "4bNQITw0VdY",
    sourceUrl: "https://e3rehab.com/how-to-perform-split-squats/",
    sourceName: "E3 Rehab",
    videoNote: "Use the standard split squat with both feet on the floor. Start with bodyweight and complete 8 reps per leg.",
    tracksOutcome: false,
  },
  {
    id: "dead_bug", name: "Dead bug", category: "Accessory",
    purpose: "Practise trunk control with alternating arm and leg movement.",
    cues: ["Lie on your back with knees bent", "Move the opposite arm and leg slowly", "Keep the lower back position steady", "Count both sides in the total reps"],
    videoId: "ZtwcT5g4Tb8",
    sourceUrl: "https://www.catalystathletics.com/exercise/494/Dead-Bug/",
    videoNote: "Start with the bent-knee variation. Move slowly for 8 reps per side; shorten the reach if your lower back starts to move.",
    tracksOutcome: false,
  },
]);

export const EXERCISE_BY_ID = Object.freeze(
  Object.fromEntries(EXERCISES.map((exercise) => [exercise.id, exercise])),
);

export const PROGRAM_DEFINITION = Object.freeze({
  schemaVersion: 1,
  id: "stability-power-base-v1",
  revision: APP_META.programRevision,
  name: "Stability & Power Base",
  reviewWindow: "8–12 weeks",
  priorities: [
    "Snatch technique and receiving stability",
    "Overhead strength and stability",
    "Competition-quality jerk lockout",
    "Specific power in the power snatch and power clean",
    "Gradual squat development",
  ],
  loadingRules: [
    "Keep technical lifts crisp and stop adding weight when positions or timing deteriorate.",
    "Keep squats at 1–3 reps in reserve in most sessions.",
    "Add 2 kg total (1 kg per side) after all prescribed work is completed successfully. Automatic targets use whole kilograms. Misses, high RPE or limited recovery hold the load.",
    "Plan near-max attempts instead of taking them every session.",
    "Tuesday, Thursday and Sunday are recovery days; easy cycling, walking or mobility is fine if it does not impair lifting.",
  ],
  reviewCriteria: [
    "More stable snatches at your working loads",
    "Progress toward your own snatch goal",
    "Improved snatch balance strength and stability",
    "Improved power-clean and power-snatch numbers",
    "Repeatable, technically legal clean & jerks",
  ],
  days: [
    {
      id: "gym_accessories",
      weekday: null,
      name: "Any day",
      title: "Gym Accessories",
      focus: "Normal gym · rack, barbell and floor space · no platform or dropped lifts",
      sessionPrompt: "Warm up first and choose familiar, comfortable loads with 2–3 reps in reserve. Rest about 2 minutes between sets. Use rack safeties, lower every rep under control and follow the gym’s rules. This is an alternative session, not extra work you must add to the full week. Log total bar weight including the bar; for bodyweight movements enter 0 kg.",
      exercises: [
        { exerciseId: "romanian_deadlift", sets: 3, reps: "8", defaultReps: 8, initialWeight: "", progression: { step: 2 },
          recommendation: "Choose a comfortable starting weight", notes: "Start and finish from the rack. Keep the bar close, lower under control and do not drop it. Record total bar weight.", priority: 1, videoRef: "romanian_deadlift" },
        { exerciseId: "strict_press", sets: 3, reps: "8", defaultReps: 8, initialWeight: "", progression: { step: 2 },
          recommendation: "Choose a comfortable starting weight", notes: "Press from the rack without leg drive. Use a lighter bar if needed and leave 2–3 reps in reserve. No jerks or dropped bars.", priority: 2, videoRef: "strict_press" },
        { exerciseId: "barbell_row", sets: 3, reps: "10", defaultReps: 10, initialWeight: "", progression: { step: 2 },
          recommendation: "Choose a comfortable starting weight", notes: "Start from the rack, hinge to row and avoid heaving. Lower every rep under control. Record total bar weight.", priority: 3, videoRef: "barbell_row" },
        { exerciseId: "split_squat", sets: 3, reps: "16 total · 8 per leg", defaultReps: 16, initialWeight: "", progression: { step: 2 },
          recommendation: "Bodyweight or a comfortable added load", notes: "One logged set is 8 reps per leg: enter 16 total reps. Enter 0 kg for bodyweight, otherwise total added weight. Use rack safeties with a barbell; bodyweight sessions stay at 0 until you choose a loaded baseline.", priority: 4, videoRef: "split_squat" },
        { exerciseId: "dead_bug", sets: 3, reps: "16 total · 8 per side", defaultReps: 16, initialWeight: 0,
          recommendation: "Bodyweight · 0 kg", notes: "Alternate sides slowly. One logged set is 8 per side: enter 16 total reps and 0 kg. No automatic weight increases.", priority: 5, videoRef: "dead_bug" },
      ],
    },
    {
      id: "monday",
      weekday: 1,
      name: "Monday",
      title: "Snatch + Back Squat",
      focus: "Receiving stability and foundational leg strength",
      exercises: [
        {
          exerciseId: "snatch",
          sets: { min: 5, max: 8, default: 6 },
          reps: "1–2",
          defaultReps: 1,
          recommendation: "70–85% of your snatch",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Pause for 2 seconds in the receiving position on technical reps.",
          priority: 1,
          videoRef: "snatch",
        },
        {
          exerciseId: "snatch_pull",
          sets: 4,
          reps: "3",
          defaultReps: 3,
          recommendation: "90–105% of your snatch",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Maintain snatch positions and speed.",
          priority: 2,
          videoRef: "snatch_pull",
        },
        {
          exerciseId: "back_squat",
          sets: 4,
          reps: "4",
          defaultReps: 4,
          recommendation: "72–80% of your back squat",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Leave 1–3 reps in reserve.",
          priority: 3,
          videoRef: "back_squat",
        },
        {
          exerciseId: "upper_back",
          sets: { min: 3, max: 4, default: 3 },
          reps: "6–10",
          defaultReps: 8,
          recommendation: "Controlled, submaximal",
          initialWeight: "",
          notes: "Choose rows or pull-ups.",
          priority: 4,
          videoRef: null,
        },
        {
          exerciseId: "trunk",
          sets: 3,
          reps: "Controlled",
          defaultReps: 10,
          recommendation: "Moderate",
          initialWeight: "",
          notes: "Choose one trunk exercise and keep the quality high.",
          priority: 5,
          videoRef: null,
        },
      ],
    },
    {
      id: "wednesday",
      weekday: 3,
      name: "Wednesday",
      title: "Clean & Jerk + Front Squat",
      focus: "Decisive jerk lockout and clean-specific leg strength",
      exercises: [
        {
          exerciseId: "clean_and_jerk",
          sets: { min: 5, max: 7, default: 6 },
          reps: "1",
          defaultReps: 1,
          recommendation: "75–88% of your clean & jerk",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Create immediate, unmistakable elbow lockout and hold it.",
          priority: 1,
          videoRef: "clean_and_jerk",
        },
        {
          exerciseId: "pause_clean",
          sets: { min: 3, max: 4, default: 3 },
          reps: "1–2",
          defaultReps: 2,
          recommendation: "Moderate",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Use a pause clean or a clean + front squat complex.",
          priority: 2,
          videoRef: "clean",
        },
        {
          exerciseId: "front_squat",
          sets: 4,
          reps: "3",
          defaultReps: 3,
          recommendation: "Choose a controlled working load",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Stay upright; leave 1–3 reps in reserve.",
          priority: 3,
          videoRef: "front_squat",
        },
        {
          exerciseId: "push_press",
          sets: 4,
          reps: "4",
          defaultReps: 4,
          recommendation: "Build gradually from your own starting load",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Drive vertically and finish every rep with a hard lockout.",
          priority: 4,
          videoRef: "push_press",
        },
        {
          exerciseId: "triceps_upper_back",
          sets: 3,
          reps: "8–12",
          defaultReps: 10,
          recommendation: "Controlled, submaximal",
          initialWeight: "",
          notes: "Select one triceps or upper-back accessory.",
          priority: 5,
          videoRef: null,
        },
      ],
    },
    {
      id: "friday",
      weekday: 5,
      name: "Friday",
      title: "Power + Overhead Stability",
      focus: "Specific power and a stable overhead receiving position",
      exercises: [
        {
          exerciseId: "power_snatch",
          sets: 5,
          reps: "2",
          defaultReps: 2,
          recommendation: "Choose a crisp, controlled load",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Receive tall and connected; do not chase borderline depth.",
          priority: 1,
          videoRef: "power_snatch",
        },
        {
          exerciseId: "snatch_balance",
          sets: 4,
          reps: "2",
          defaultReps: 2,
          recommendation: "Choose a stable, controlled load",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Emphasize speed under the bar and a stable bottom position.",
          priority: 2,
          videoRef: "snatch_balance",
        },
        {
          exerciseId: "overhead_squat",
          sets: 3,
          reps: "3",
          defaultReps: 3,
          recommendation: "Moderate",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Pause for 3 seconds in the bottom of every rep.",
          priority: 3,
          videoRef: "overhead_squat",
        },
        {
          exerciseId: "power_clean",
          sets: 5,
          reps: "2",
          defaultReps: 2,
          recommendation: "Choose a crisp, controlled load",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Keep each lift crisp and establish your own working load.",
          priority: 4,
          videoRef: "power_clean",
        },
        {
          exerciseId: "posterior_chain",
          sets: 3,
          reps: "5–8",
          defaultReps: 6,
          recommendation: "Optional · moderate",
          initialWeight: "",
          notes: "Skip this if it would interfere with Saturday's coached session.",
          priority: 5,
          videoRef: null,
          optional: true,
        },
      ],
    },
    {
      id: "saturday",
      weekday: 6,
      name: "Saturday",
      title: "Coached Session",
      focus: "Competition lifts, coach feedback and repeatable execution",
      exercises: [
        {
          exerciseId: "snatch",
          sets: { min: 1, max: 10, default: 5 },
          reps: "Coach determines",
          defaultReps: 1,
          recommendation: "Coach determines intensity",
          initialWeight: "",
          notes: "Focus on receiving position, stability and repeatability.",
          priority: 1,
          videoRef: "snatch",
        },
        {
          exerciseId: "clean_and_jerk",
          sets: { min: 1, max: 10, default: 5 },
          reps: "Coach determines",
          defaultReps: 1,
          recommendation: "Coach determines intensity",
          initialWeight: "",
          notes: "Focus on a legal, decisive jerk lockout.",
          priority: 2,
          videoRef: "clean_and_jerk",
        },
      ],
      sessionPrompt: "Record only 1–2 actionable cues from your coach. Keep athlete observations and coach cues separate.",
    },
  ],
});
