// Shared programme and exercise catalogue. No athlete profile or personal records.
export const APP_META = Object.freeze({
  name: "Lift Journal",
  dataSchemaVersion: 2,
  programSchemaVersion: 1,
  programRevision: "2026-09-05",
});

// Shared search and logging metadata for existing IDs; historical records retain their IDs.
const existingExerciseMetadata = [
  {
    ids: ["back_squat", "front_squat"],
    muscles: ["Quadriceps", "Glutes", "Core"],
    disciplines: ["gym", "olympic"],
  },
  {
    ids: ["push_press", "strict_press"],
    aliases: ["overhead press", "military press"],
    muscles: ["Shoulders", "Triceps"],
    disciplines: ["gym", "olympic"],
  },
  {
    ids: ["romanian_deadlift"],
    aliases: ["RDL", "barbell RDL"],
    muscles: ["Hamstrings", "Glutes", "Back"],
    disciplines: ["gym", "olympic"],
  },
  {
    ids: ["barbell_row"],
    aliases: ["bent over row", "bent row"],
    muscles: ["Back", "Biceps"],
    disciplines: ["gym", "olympic"],
  },
  {
    ids: ["split_squat"],
    muscles: ["Quadriceps", "Glutes"],
    equipment: ["Bodyweight", "Dumbbells", "Barbell"],
    disciplines: ["gym", "olympic"],
    loggingNotes:
      "Log 0 kg for bodyweight, or only the additional weight when loaded. With two dumbbells, log their combined weight. Count reps across both sides: 8 per side = 16 total reps.",
  },
  {
    ids: ["dead_bug"],
    aliases: ["deadbug"],
    muscles: ["Core"],
    equipment: ["Bodyweight"],
    disciplines: ["gym", "olympic"],
    loggingNotes:
      "Log 0 kg. Count reps across both sides: 8 per side = 16 total reps.",
  },
  {
    ids: ["upper_back", "trunk", "triceps_upper_back", "posterior_chain"],
    muscles: [],
    equipment: [],
    loggingNotes:
      "Choose a specific exercise for consistent weight and rep tracking.",
    sourceName: "",
  },
];

// The video IDs below are kept in data rather than UI code so a video can be
// replaced without touching the workout or library rendering logic.
export const EXERCISES = Object.freeze(
  [
    {
      id: "snatch",
      name: "Snatch",
      category: "Snatch",
      purpose:
        "Build the competition lift and a confident, stable receiving position.",
      cues: [
        "Push through the whole foot",
        "Stay close, then pull under",
        "Punch up and own the bottom",
      ],
      videoId: "1Lv1IyigIUY",
      sourceUrl: "https://www.catalystathletics.com/exercise/58/Snatch/",
      tracksOutcome: true,
    },
    {
      id: "power_snatch",
      name: "Power snatch",
      category: "Snatch",
      purpose:
        "Develop explosive extension, a fast turnover and precise high receiving mechanics.",
      cues: [
        "Finish the leg drive",
        "Meet the bar actively",
        "Receive upright above parallel",
      ],
      videoId: "ydHHsju1-Nc",
      sourceUrl: "https://www.catalystathletics.com/exercise/61/Power-Snatch/",
      tracksOutcome: true,
    },
    {
      id: "snatch_pull",
      name: "Snatch pull",
      category: "Snatch",
      purpose:
        "Strengthen snatch positions and vertical acceleration with more load than the full lift.",
      cues: [
        "Keep the bar close",
        "Hold the back angle past the knee",
        "Extend vertically with speed",
      ],
      videoId: "G1QygZ3Kd3w",
      sourceUrl: "https://www.catalystathletics.com/exercise/97/Snatch-Pull/",
      tracksOutcome: false,
    },
    {
      id: "snatch_balance",
      name: "Snatch balance",
      category: "Overhead",
      purpose:
        "Train speed under the bar, receiving strength and confidence in the snatch bottom.",
      cues: [
        "Dip smoothly and vertically",
        "Move down; do not launch the bar",
        "Punch and stabilize immediately",
      ],
      videoId: "O2anVg-_tLQ",
      sourceUrl:
        "https://www.catalystathletics.com/video/1577/Snatch-Balance-Variations/",
      tracksOutcome: true,
    },
    {
      id: "overhead_squat",
      name: "Overhead squat",
      category: "Overhead",
      purpose:
        "Build mobility, balance and strength in the snatch receiving position.",
      cues: [
        "Set the upper back",
        "Stay balanced over the whole foot",
        "Push up into the bar",
      ],
      videoId: "2Nntfq9mDfg",
      sourceUrl:
        "https://www.catalystathletics.com/exercise/79/Overhead-Squat/",
      tracksOutcome: false,
    },
    {
      id: "clean",
      name: "Clean",
      category: "Clean",
      purpose:
        "Develop the competition clean from the floor through a strong rack and recovery.",
      cues: [
        "Push from the floor",
        "Keep the bar close",
        "Turn over fast and drive out of the bottom",
      ],
      videoId: "oQIaWLrB318",
      sourceUrl: "https://www.catalystathletics.com/exercise/59/Clean/",
      tracksOutcome: true,
    },
    {
      id: "pause_clean",
      name: "Pause clean",
      category: "Clean",
      purpose:
        "Reinforce balance and exact pulling positions before a fast finish and turnover.",
      cues: [
        "Pause without losing tension",
        "Stay balanced over the whole foot",
        "Accelerate after the pause",
      ],
      videoId: "oQIaWLrB318",
      sourceUrl:
        "https://www.catalystathletics.com/exercise/323/Clean-Segment-Clean/",
      tracksOutcome: true,
    },
    {
      id: "power_clean",
      name: "Power clean",
      category: "Clean",
      purpose:
        "Build specific power, a complete extension and an active high rack.",
      cues: [
        "Finish with the legs",
        "Pull under instead of curling",
        "Meet the bar with an upright trunk",
      ],
      videoId: "YG8M_-11C2A",
      sourceUrl: "https://www.catalystathletics.com/exercise/67/Power-Clean/",
      tracksOutcome: true,
    },
    {
      id: "clean_pull",
      name: "Clean pull",
      category: "Clean",
      purpose:
        "Build clean-specific pulling strength while preserving balance, posture and speed.",
      cues: [
        "Push the floor away",
        "Keep the bar against the body",
        "Extend vertically; finish tall",
      ],
      videoId: "xx8WkFrST2Y",
      sourceUrl: "https://www.catalystathletics.com/exercise/98/Clean-Pull/",
      tracksOutcome: false,
    },
    {
      id: "clean_and_jerk",
      name: "Clean & jerk",
      category: "Competition",
      purpose:
        "Practice the complete competition lift with a decisive, legal overhead lockout.",
      cues: [
        "Make the clean precise",
        "Reset before the jerk",
        "Punch to immediate lockout and hold",
      ],
      videoId: "bNCXgyosXlc",
      sourceUrl: "https://www.catalystathletics.com/exercise/76/Clean-Jerk/",
      tracksOutcome: true,
    },
    {
      id: "jerk",
      name: "Jerk",
      category: "Jerk",
      purpose:
        "Develop an efficient drive, fast split and unmistakable overhead fixation.",
      cues: [
        "Dip straight and stay connected",
        "Drive through the bar",
        "Punch fast, lock immediately, then recover",
      ],
      videoId: "2GPA-cjUFnA",
      sourceUrl: "https://www.catalystathletics.com/exercise/60/Split-Jerk/",
      tracksOutcome: true,
    },
    {
      id: "push_press",
      name: "Push press",
      category: "Jerk",
      purpose:
        "Build overhead strength while rehearsing the dip, drive and arm timing of the jerk.",
      cues: [
        "Dip vertically",
        "Finish the leg drive",
        "Press up and slightly back to a hard lockout",
      ],
      videoId: "dhZlP5NX-wo",
      sourceUrl: "https://www.catalystathletics.com/exercise/87/Push-Press/",
      tracksOutcome: false,
    },
    {
      id: "back_squat",
      name: "Back squat",
      category: "Strength",
      purpose:
        "Build leg and trunk strength with a barbell held across your upper back.",
      cues: [
        "Brace before descending",
        "Keep whole-foot balance",
        "Drive up without losing posture",
      ],
      videoId: "Akd5xmZlsvg",
      sourceUrl: "https://www.catalystathletics.com/exercise/77/Back-Squat/",
      tracksOutcome: false,
    },
    {
      id: "front_squat",
      name: "Front squat",
      category: "Strength",
      purpose:
        "Build leg strength and an upright squat with the bar held in the front rack.",
      cues: [
        "Lift the elbows",
        "Brace and stay upright",
        "Drive straight out of the bottom",
      ],
      videoId: "lNJ3DyibYZQ",
      sourceUrl: "https://www.catalystathletics.com/exercise/78/Front-Squat/",
      tracksOutcome: false,
    },
    {
      id: "upper_back",
      name: "Rows / pull-ups",
      category: "Accessory",
      purpose: "Support upper-back strength and bar control.",
      cues: [
        "Use a full range",
        "Keep the trunk controlled",
        "Stop before technique changes",
      ],
      videoId: null,
      sourceUrl: null,
      tracksOutcome: false,
    },
    {
      id: "trunk",
      name: "Trunk work",
      category: "Accessory",
      purpose:
        "Build bracing capacity that transfers to pulls, squats and overhead positions.",
      cues: [
        "Choose one focused movement",
        "Brace without holding your breath too long",
        "Keep reps controlled",
      ],
      videoId: null,
      sourceUrl: null,
      tracksOutcome: false,
    },
    {
      id: "triceps_upper_back",
      name: "Triceps / upper back",
      category: "Accessory",
      purpose: "Support jerk lockout strength and upper-back position.",
      cues: [
        "Use controlled reps",
        "Choose pain-free movements",
        "Leave a little in reserve",
      ],
      videoId: null,
      sourceUrl: null,
      tracksOutcome: false,
    },
    {
      id: "posterior_chain",
      name: "Posterior chain",
      category: "Accessory",
      purpose:
        "Add optional hamstring, glute and back strength without compromising recovery.",
      cues: [
        "Choose a familiar hinge",
        "Keep the back set",
        "Skip it if recovery is poor",
      ],
      videoId: null,
      sourceUrl: null,
      tracksOutcome: false,
    },
    {
      id: "romanian_deadlift",
      name: "Romanian deadlift",
      category: "Accessory",
      purpose:
        "Train the hamstrings and glutes with a controlled barbell hinge.",
      cues: [
        "Unrack the bar and brace",
        "Push the hips back with soft knees",
        "Keep the bar close; lower only as far as your position allows",
        "Return the bar to the rack without dropping it",
      ],
      videoId: "_U9KjljQyd0",
      sourceUrl:
        "https://www.catalystathletics.com/exercise/101/Romanian-Deadlift-RDL/",
      tracksOutcome: false,
    },
    {
      id: "strict_press",
      name: "Strict press",
      category: "Accessory",
      purpose: "Build overhead strength with a controlled press from the rack.",
      cues: [
        "Brace and keep the ribs down",
        "Press without a leg drive",
        "Lower to the shoulders under control and re-rack",
      ],
      videoId: "_cfNP_VXs_U",
      sourceUrl: "https://www.catalystathletics.com/exercise/90/Press/",
      tracksOutcome: false,
    },
    {
      id: "barbell_row",
      name: "Barbell row",
      category: "Accessory",
      purpose: "Build upper-back strength using a controlled pulling movement.",
      cues: [
        "Set the bar in the rack to start",
        "Hinge and keep your torso steady",
        "Pull toward the lower ribs without jerking",
        "Lower under control",
      ],
      videoId: "D4eruYL5_Fc",
      sourceUrl: "https://www.catalystathletics.com/exercise/171/Bent-Row/",
      tracksOutcome: false,
    },
    {
      id: "split_squat",
      name: "Split squat",
      category: "Accessory",
      purpose:
        "Train single-leg strength and control from a stable split stance.",
      cues: [
        "Start with bodyweight if needed",
        "Keep the front foot planted",
        "Use the rack safeties if loading a barbell",
        "Complete both legs before logging the set",
      ],
      videoId: "4bNQITw0VdY",
      sourceUrl: "https://e3rehab.com/how-to-perform-split-squats/",
      sourceName: "E3 Rehab",
      videoNote:
        "Use the standard split squat with both feet on the floor. Start with bodyweight and complete 8 reps per leg.",
      tracksOutcome: false,
    },
    {
      id: "dead_bug",
      name: "Dead bug",
      category: "Accessory",
      purpose: "Practise trunk control with alternating arm and leg movement.",
      cues: [
        "Lie on your back with knees bent",
        "Move the opposite arm and leg slowly",
        "Keep the lower back position steady",
        "Count both sides in the total reps",
      ],
      videoId: "ZtwcT5g4Tb8",
      sourceUrl: "https://www.catalystathletics.com/exercise/494/Dead-Bug/",
      videoNote:
        "Start with the bent-knee variation. Move slowly for 8 reps per side; shorten the reach if your lower back starts to move.",
      tracksOutcome: false,
    },
    {
      id: "bench_press",
      name: "Barbell bench press",
      category: "Chest",
      purpose: "Build chest and pressing strength on a flat bench.",
      cues: [
        "Plant your feet and set your shoulder blades",
        "Lower the bar toward mid-chest with control",
        "Press up with your hips on the bench; use safeties or a spotter",
      ],
      aliases: ["bench press", "flat bench", "barbell chest press"],
      muscles: ["Chest", "Triceps", "Shoulders"],
      equipment: ["Barbell", "Bench"],
      disciplines: ["gym"],
      loggingNotes: "Log total weight including the bar.",
      videoId: "CjHIKDQ4RQo",
      videoTitle: "How To Do A Barbell Bench Press Correctly",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/chest/bench-press/barbell-bench-press/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "dumbbell_bench_press",
      name: "Dumbbell bench press",
      category: "Chest",
      purpose: "Train the chest with independent dumbbells on a flat bench.",
      cues: [
        "Keep feet planted and shoulder blades supported",
        "Lower the dumbbells beside your chest",
        "Press smoothly without bouncing or clashing the weights",
      ],
      aliases: ["DB bench press", "flat dumbbell press"],
      muscles: ["Chest", "Triceps", "Shoulders"],
      equipment: ["Dumbbells", "Bench"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the combined weight of both dumbbells: two 20 kg dumbbells = 40 kg. One simultaneous repetition counts as one rep.",
      videoId: "AduT4Eq-iP0",
      videoTitle: "How To Do A Dumbbell Bench Press",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/chest/bench-press/dumbbell-bench-press/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "incline_dumbbell_press",
      name: "Incline dumbbell press",
      category: "Chest",
      purpose: "Train the chest and shoulders using an inclined bench.",
      cues: [
        "Set a modest bench incline and plant your feet",
        "Lower with wrists stacked above elbows",
        "Keep your back supported as you press",
      ],
      aliases: ["incline DB bench press", "upper chest press"],
      muscles: ["Chest", "Shoulders", "Triceps"],
      equipment: ["Dumbbells", "Bench"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the combined weight of both dumbbells: two 20 kg dumbbells = 40 kg. One simultaneous repetition counts as one rep.",
      videoId: "oZVCBM9f8Eo",
      videoTitle: "How To Do A Dumbbell Incline Press",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/chest/bench-press/incline-dumbbell-press/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "chest_press_machine",
      name: "Machine chest press",
      category: "Chest",
      purpose: "Train pressing strength with a supported machine movement.",
      cues: [
        "Adjust the seat so handles line up with your chest",
        "Keep your back against the pad",
        "Press and return without letting the stack crash",
      ],
      aliases: ["seated chest press", "chest press machine"],
      muscles: ["Chest", "Triceps", "Shoulders"],
      equipment: ["Machine"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the selected machine weight in kg. Compare progress on the same machine and record the machine or settings in notes.",
      videoId: "CIykDiF4sfg",
      videoTitle: "How To Do A Seated Chest Press",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/chest/bench-press/seated-chest-press/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "cable_fly",
      name: "Cable chest fly",
      category: "Chest",
      purpose:
        "Train the chest through a controlled shoulder-height cable arc.",
      cues: [
        "Use shoulder-height pulleys and a stable staggered stance",
        "Keep a soft, steady bend in your elbows",
        "Bring your hands together in front of your chest, then return slowly",
      ],
      aliases: ["cable crossover", "cable flyes", "cable pec fly"],
      muscles: ["Chest"],
      equipment: ["Cable"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the combined selected weight of both stacks: 5 kg per side = 10 kg. Compare on the same cable machine.",
      videoId: "QcTcWpkn_bw",
      videoTitle: "How To Do A Cable Fly/ Cable Crossover",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/chest/chest-fly/cable-flyes/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "push_up",
      name: "Push-up",
      category: "Chest",
      purpose: "Build pressing strength and trunk control with bodyweight.",
      cues: [
        "Keep shoulders, hips and heels aligned",
        "Lower your chest between your hands",
        "Push the floor away without letting your hips sag",
      ],
      aliases: ["push up", "press up", "press-up"],
      muscles: ["Chest", "Triceps", "Core"],
      equipment: ["Bodyweight"],
      disciplines: ["gym"],
      loggingNotes:
        "Log 0 kg for bodyweight, or only the additional weight when loaded.",
      videoId: "Env8gAr_QnE",
      videoTitle: "How To Do Press Ups",
      videoAuthor: "PureGym",
      sourceUrl: "https://www.puregym.com/exercises/chest/press-up/push-ups/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "lat_pulldown",
      name: "Lat pulldown",
      category: "Back",
      purpose: "Train vertical pulling strength with a front-of-body pulldown.",
      cues: [
        "Secure the thigh pad and brace your torso",
        "Pull the bar toward your upper chest",
        "Let your arms extend again without swinging",
      ],
      aliases: ["lat pull down", "wide grip pulldown"],
      muscles: ["Back", "Biceps"],
      equipment: ["Cable", "Machine"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the selected machine weight in kg. Compare progress on the same machine and record the machine or settings in notes.",
      videoId: "JGeRYIZdojU",
      videoTitle: "How To Do A Lat Pulldown",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/back/lat-exercises/lat-pulldown/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "seated_cable_row",
      name: "Seated cable row",
      category: "Back",
      purpose: "Train the back with a seated horizontal pull.",
      cues: [
        "Sit tall with knees slightly bent",
        "Draw the handle toward your lower ribs",
        "Return with control and avoid rocking your torso",
      ],
      aliases: ["low cable row", "seated row"],
      muscles: ["Back", "Biceps"],
      equipment: ["Cable"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the selected machine weight in kg. Compare progress on the same machine and record the machine or settings in notes.",
      videoId: "lJoozxC0Rns",
      videoTitle: "How To Do A Seated Cable Row",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/back/rows/seated-cable-row/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "dumbbell_row",
      name: "Single-arm dumbbell row",
      category: "Back",
      purpose: "Train each side of the back with support from a bench.",
      cues: [
        "Support your free hand and keep your back steady",
        "Pull the dumbbell toward your hip",
        "Lower fully without twisting your torso",
      ],
      aliases: ["one arm row", "single arm DB row", "dumbbell row"],
      muscles: ["Back", "Biceps"],
      equipment: ["Dumbbells", "Bench"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the weight of the single dumbbell being lifted. Count reps across both sides: 8 per side = 16 total reps.",
      videoId: "ZRSGpBUVcNw",
      videoTitle: "How To Do Single Arm Dumbbell Rows",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/back/rows/single-arm-dumbbell-row/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "pull_up",
      name: "Pull-up",
      category: "Back",
      purpose: "Build vertical pulling strength with an overhand grip.",
      cues: [
        "Start with arms extended and a secure grip",
        "Pull your elbows down as your chin reaches the bar",
        "Lower smoothly without kicking or swinging",
      ],
      aliases: ["pull up", "overhand pullup"],
      muscles: ["Back", "Biceps"],
      equipment: ["Bodyweight", "Pull-up bar"],
      disciplines: ["gym"],
      loggingNotes:
        "Log 0 kg for bodyweight, or only the additional weight when loaded. For assisted reps, record band or machine assistance in notes; do not enter assistance as added weight.",
      videoId: "PHdHnZcbsB8",
      videoTitle: "How To Do Pull Ups",
      videoAuthor: "PureGym",
      sourceUrl: "https://www.puregym.com/exercises/back/pull-up/pull-ups/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "dumbbell_shoulder_press",
      name: "Dumbbell shoulder press",
      category: "Shoulders",
      purpose: "Build overhead pressing strength from a standing position.",
      cues: [
        "Brace your trunk and keep your ribs down",
        "Press from shoulder height without a leg drive",
        "Lower both dumbbells with control",
      ],
      aliases: ["DB overhead press", "dumbbell overhead press"],
      muscles: ["Shoulders", "Triceps"],
      equipment: ["Dumbbells"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the combined weight of both dumbbells: two 20 kg dumbbells = 40 kg. One simultaneous repetition counts as one rep.",
      videoId: "aI2hGzsAMXs",
      videoTitle: "How To Do A Dumbbell Shoulder Press",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/arms-and-shoulders/shoulder-press/dumbbell-shoulder-press/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "lateral_raise",
      name: "Dumbbell lateral raise",
      category: "Shoulders",
      purpose: "Train the side of the shoulders with light, controlled raises.",
      cues: [
        "Keep a soft bend in your elbows",
        "Raise out to the sides to about shoulder height",
        "Lower slowly without swinging your body",
      ],
      aliases: ["side raise", "DB lateral raise"],
      muscles: ["Shoulders"],
      equipment: ["Dumbbells"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the combined weight of both dumbbells: two 20 kg dumbbells = 40 kg. One simultaneous repetition counts as one rep.",
      videoId: "z-kOn7flIZg",
      videoTitle: "How To Do Lateral Raises",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/arms-and-shoulders/lateral-raises/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "face_pull",
      name: "Cable face pull",
      category: "Shoulders",
      purpose:
        "Train the rear shoulders and upper back using a rope attachment.",
      cues: [
        "Set a rope around upper-chest height and step back",
        "Pull toward your face, separating the rope ends",
        "Keep your torso steady as you return",
      ],
      aliases: ["rope face pull", "rear delt cable"],
      muscles: ["Shoulders", "Back"],
      equipment: ["Cable"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the selected machine weight in kg. Compare progress on the same machine and record the machine or settings in notes.",
      videoId: "0Po47vvj9g4",
      videoTitle: "How To Do Cable Face Pulls",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/arms-and-shoulders/rear-delt-exercises/face-pulls/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "reverse_fly",
      name: "Dumbbell reverse fly",
      category: "Shoulders",
      purpose: "Train the rear shoulders from a steady hip hinge.",
      cues: [
        "Hinge at your hips with a steady back",
        "Lift the dumbbells out with softly bent elbows",
        "Use a light load and avoid shrugging or heaving",
      ],
      aliases: ["rear delt fly", "rear delt flyes", "reverse dumbbell fly"],
      muscles: ["Shoulders", "Back"],
      equipment: ["Dumbbells"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the combined weight of both dumbbells: two 20 kg dumbbells = 40 kg. One simultaneous repetition counts as one rep.",
      videoId: "nlkF7_2O_Lw",
      videoTitle: "How To Do A Rear Delt Fly",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/arms-and-shoulders/rear-delt-exercises/rear-delt-flyes/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "dumbbell_curl",
      name: "Dumbbell biceps curl",
      category: "Arms",
      purpose: "Train the biceps by curling both dumbbells together.",
      cues: [
        "Keep your elbows near your sides",
        "Curl both weights without swinging your hips",
        "Lower until your arms extend comfortably",
      ],
      aliases: ["DB curl", "bicep curl", "double arm curl"],
      muscles: ["Biceps"],
      equipment: ["Dumbbells"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the combined weight of both dumbbells: two 20 kg dumbbells = 40 kg. One simultaneous repetition counts as one rep.",
      videoId: "MtXdEcW3Eog",
      videoTitle: "How To Double Arm Curl (Dumbbell Bicep Curl)",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/arms-and-shoulders/bicep-curl/dumbbell-bicep-curls/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "hammer_curl",
      name: "Hammer curl",
      category: "Arms",
      purpose: "Train elbow flexion with palms facing inward.",
      cues: [
        "Keep your palms facing each other",
        "Curl with your upper arms still",
        "Lower slowly rather than dropping the weights",
      ],
      aliases: ["neutral grip curl", "DB hammer curl"],
      muscles: ["Biceps"],
      equipment: ["Dumbbells"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the combined weight of both dumbbells: two 20 kg dumbbells = 40 kg. One simultaneous repetition counts as one rep. If alternating arms, count total reps across both arms.",
      videoId: "B4RznoFvTl4",
      videoTitle: "How To Do Hammer Curls",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/arms-and-shoulders/bicep-curl/hammer-curls/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "cable_triceps_pushdown",
      name: "Cable triceps pushdown",
      category: "Arms",
      purpose: "Train the triceps with a high-pulley pressdown.",
      cues: [
        "Keep your elbows close to your torso",
        "Extend your elbows without leaning onto the rope",
        "Return slowly while keeping your upper arms still",
      ],
      aliases: ["tricep pushdown", "triceps pressdown", "rope pushdown"],
      muscles: ["Triceps"],
      equipment: ["Cable"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the selected machine weight in kg. Compare progress on the same machine and record the machine or settings in notes.",
      videoId: "LXkCrxn3caQ",
      videoTitle: "How To Do A Tricep Pushdown",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/arms-and-shoulders/tricep-extension/tricep-pushdowns/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "overhead_triceps_extension",
      name: "Dumbbell overhead triceps extension",
      category: "Arms",
      purpose: "Train the triceps using one dumbbell held with both hands.",
      cues: [
        "Hold one dumbbell securely overhead",
        "Bend your elbows to lower it behind your head",
        "Extend your arms while keeping your ribs down",
      ],
      aliases: ["overhead tricep extension", "French press"],
      muscles: ["Triceps"],
      equipment: ["Dumbbells"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the weight of the single dumbbell held in both hands. One extension counts as one rep.",
      videoId: "9wxRhONFsRA",
      videoTitle: "How To Do An Overhead Tricep Extension",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/arms-and-shoulders/tricep-extension/overhead-tricep-extension/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "deadlift",
      name: "Conventional deadlift",
      category: "Legs",
      purpose: "Build whole-body pulling strength from the floor.",
      cues: [
        "Start with the bar over midfoot and brace",
        "Push through your feet with the bar close",
        "Stand tall, then lower with a controlled hip hinge",
      ],
      aliases: ["barbell deadlift", "conventional barbell deadlift"],
      muscles: ["Hamstrings", "Glutes", "Back"],
      equipment: ["Barbell"],
      disciplines: ["gym"],
      loggingNotes: "Log total weight including the bar.",
      videoId: "GxsLrTzyGUU",
      videoTitle: "How to Do A Conventional Deadlift Correctly",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/legs/hamstring-exercises/deadlifts/conventional-deadlift/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "goblet_squat",
      name: "Goblet squat",
      category: "Legs",
      purpose: "Train a squat while holding one weight in front of your chest.",
      cues: [
        "Hold the weight close to your chest",
        "Sit down between your hips with heels planted",
        "Stand up while keeping your torso braced",
      ],
      aliases: ["DB goblet squat", "kettlebell squat"],
      muscles: ["Quadriceps", "Glutes", "Core"],
      equipment: ["Dumbbells", "Kettlebell"],
      disciplines: ["gym"],
      loggingNotes: "Log the weight of the single dumbbell or kettlebell.",
      videoId: "zBV3ceGyAxw",
      videoTitle: "How To Do A Goblet squat",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/legs/quad-exercises/squats/goblet-squat/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "leg_press",
      name: "Seated leg press",
      category: "Legs",
      purpose: "Train the legs using a seated leg press machine.",
      cues: [
        "Keep your back and hips against the pad",
        "Lower only as far as your pelvis stays supported",
        "Press through your feet without snapping your knees straight",
      ],
      aliases: ["leg press machine", "horizontal leg press"],
      muscles: ["Quadriceps", "Glutes"],
      equipment: ["Machine"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the selected machine weight in kg. Compare progress on the same machine and record the machine or settings in notes.",
      videoId: "qCR9bN3G1t4",
      videoTitle: "How To Do A Seated Leg Press",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/legs/quad-exercises/leg-presses/seated-leg-press/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "leg_extension",
      name: "Leg extension",
      category: "Legs",
      purpose: "Train the front of the thighs on a leg extension machine.",
      cues: [
        "Align your knees with the machine pivot",
        "Extend your legs without lifting your hips",
        "Lower the pad slowly",
      ],
      aliases: ["quad extension", "knee extension machine"],
      muscles: ["Quadriceps"],
      equipment: ["Machine"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the selected machine weight in kg. Compare progress on the same machine and record the machine or settings in notes.",
      videoId: "4ZDm5EbiFI8",
      videoTitle: "How To Do A Leg Extension",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/legs/quad-exercises/leg-extensions/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "seated_leg_curl",
      name: "Seated leg curl",
      category: "Legs",
      purpose:
        "Train the hamstrings by bending your knees on a seated machine.",
      cues: [
        "Adjust the seat, ankle roller and thigh restraint",
        "Keep your hips and back supported as you curl",
        "Return to the start slowly without lifting the stack",
      ],
      aliases: ["hamstring curl", "seated hamstring curl"],
      muscles: ["Hamstrings"],
      equipment: ["Machine"],
      disciplines: ["gym"],
      loggingNotes:
        "Log the selected machine weight in kg. Compare progress on the same machine and record the machine or settings in notes.",
      videoId: "_2Kd0d-JEUM",
      videoTitle:
        "How to do a Seated Leg Curl  | Proper Form & Technique | NASM",
      videoAuthor: "National Academy of Sports Medicine (NASM)",
      sourceUrl:
        "https://www.nasm.org/resource-center/exercise-library/seated-leg-curl",
      sourceName: "NASM",
      tracksOutcome: false,
    },
    {
      id: "hip_thrust",
      name: "Barbell hip thrust",
      category: "Glutes",
      purpose: "Train hip extension with your upper back supported on a bench.",
      cues: [
        "Support your upper back and pad the bar at your hips",
        "Push through your feet to raise your hips",
        "Finish with ribs down, then lower without overextending your back",
      ],
      aliases: ["hip thrust", "barbell glute thrust"],
      muscles: ["Glutes", "Hamstrings"],
      equipment: ["Barbell", "Bench"],
      disciplines: ["gym"],
      loggingNotes: "Log total weight including the bar.",
      videoId: "aweBS7K71l8",
      videoTitle: "How To Do A Barbell Hip Thrust",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/glutes/hip-thrusts/barbell-hip-thrust/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "glute_bridge",
      name: "Glute bridge",
      category: "Glutes",
      purpose: "Train hip extension while lying on the floor.",
      cues: [
        "Plant your feet with knees bent",
        "Lift your hips by squeezing your glutes",
        "Lower without arching your lower back",
      ],
      aliases: ["floor bridge", "hip bridge"],
      muscles: ["Glutes", "Hamstrings"],
      equipment: ["Bodyweight"],
      disciplines: ["gym"],
      loggingNotes:
        "Log 0 kg for bodyweight, or only the additional weight when loaded.",
      videoId: "tqp5XQPpTxY",
      videoTitle: "How To Do A Glute Bridge",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/glutes/glute-bridge/glute-bridges/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "bulgarian_split_squat",
      name: "Bulgarian split squat",
      category: "Legs",
      purpose: "Train one leg at a time with the rear foot raised on a bench.",
      cues: [
        "Rest the rear foot on a stable bench",
        "Lower with your front foot planted",
        "Push through the front leg and repeat on both sides",
      ],
      aliases: ["rear foot elevated split squat", "RFESS"],
      muscles: ["Quadriceps", "Glutes"],
      equipment: ["Bodyweight", "Dumbbells", "Bench"],
      disciplines: ["gym"],
      loggingNotes:
        "Log 0 kg for bodyweight, or only the additional weight when loaded. With two dumbbells, log their combined weight. Count reps across both sides: 8 per side = 16 total reps.",
      videoId: "TEXl2b3__S4",
      videoTitle: "How To Do Bulgarian Split Squats",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/legs/quad-exercises/squats/bulgarian-split-squat/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "reverse_lunge",
      name: "Reverse lunge",
      category: "Legs",
      purpose: "Train single-leg strength by stepping backward into a lunge.",
      cues: [
        "Step back far enough to stay balanced",
        "Lower both knees with your front foot planted",
        "Push through the front leg to return to standing",
      ],
      aliases: ["backward lunge", "reverse lunges"],
      muscles: ["Quadriceps", "Glutes"],
      equipment: ["Bodyweight", "Dumbbells"],
      disciplines: ["gym"],
      loggingNotes:
        "Log 0 kg for bodyweight, or only the additional weight when loaded. With two dumbbells, log their combined weight. Count reps across both sides: 8 per side = 16 total reps.",
      videoId: "xrPteyQLGAo",
      videoTitle: "How To Reverse Lunge",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/legs/quad-exercises/lunges/reverse-lunges/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "standing_calf_raise",
      name: "Standing calf raise",
      category: "Legs",
      purpose: "Train the calves by lifting and lowering your heels.",
      cues: [
        "Keep your body steady; use support if needed",
        "Rise onto the balls of both feet",
        "Pause, then lower your heels with control",
      ],
      aliases: ["calf raises", "heel raise"],
      muscles: ["Calves"],
      equipment: ["Bodyweight", "Dumbbells"],
      disciplines: ["gym"],
      loggingNotes:
        "Log 0 kg for bodyweight, or only the additional weight when loaded. With two dumbbells, log their combined weight.",
      videoId: "Zep-wKHWkNM",
      videoTitle: "How To Do Calf Raises",
      videoAuthor: "PureGym",
      sourceUrl:
        "https://www.puregym.com/exercises/legs/calf-exercises/calf-raises/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "hanging_knee_raise",
      name: "Hanging knee raise",
      category: "Core",
      purpose: "Train the abdominal muscles by raising both knees from a hang.",
      cues: [
        "Use a secure grip and steady your body",
        "Curl both knees up without swinging",
        "Lower slowly before the next repetition",
      ],
      aliases: ["hanging knee raises", "hanging abs"],
      muscles: ["Core"],
      equipment: ["Bodyweight", "Pull-up bar"],
      disciplines: ["gym"],
      loggingNotes:
        "Log 0 kg for bodyweight, or only the additional weight when loaded. Raising both knees together counts as one rep.",
      videoId: "O7iDA3ory-w",
      videoTitle: "How To Do Hanging Knee Raises",
      videoAuthor: "PureGym",
      sourceUrl: "https://www.puregym.com/exercises/abs/hanging-knee-raises/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
    {
      id: "crunch",
      name: "Abdominal crunch",
      category: "Core",
      purpose: "Train abdominal flexion with a small, controlled floor curl.",
      cues: [
        "Keep your knees bent and feet on the floor",
        "Curl your shoulders up while the lower back stays down",
        "Lower slowly without pulling on your neck",
      ],
      aliases: ["ab crunch", "abs crunch", "crunches"],
      muscles: ["Core"],
      equipment: ["Bodyweight"],
      disciplines: ["gym"],
      loggingNotes:
        "Log 0 kg for bodyweight, or only the additional weight when loaded.",
      videoId: "NnVhqMQRvmM",
      videoTitle: "AB EXERCISE - How to do an abdominal crunch (ab crunch)",
      videoAuthor: "PureGym",
      sourceUrl: "https://www.puregym.com/exercises/abs/crunches/",
      sourceName: "PureGym",
      tracksOutcome: false,
    },
  ].map((exercise) => {
    const { ids: _ids, ...metadata } =
      existingExerciseMetadata.find((item) => item.ids.includes(exercise.id)) ??
      {};
    return Object.freeze({
      aliases: [],
      muscles: ["Quadriceps", "Glutes", "Back", "Shoulders"],
      equipment: ["Barbell"],
      disciplines: ["olympic"],
      loggingNotes: "Log total weight including the bar.",
      sourceName: "Catalyst Athletics",
      videoTitle: "",
      videoAuthor: "",
      videoNote: "",
      ...metadata,
      ...exercise,
    });
  }),
);

export const EXERCISE_BY_ID = Object.freeze(
  Object.fromEntries(EXERCISES.map((exercise) => [exercise.id, exercise])),
);

export const PROGRAM_DEFINITION = Object.freeze({
  schemaVersion: 1,
  id: "stability-power-base-v1",
  revision: APP_META.programRevision,
  name: "Stability & Power Base",
  reviewWindow: "8–12 weeks",
  priorities: [
    "Snatch technique and receiving stability",
    "Overhead strength and stability",
    "Competition-quality jerk lockout",
    "Specific power in the power snatch and power clean",
    "Gradual squat development",
  ],
  loadingRules: [
    "Keep technical lifts crisp and stop adding weight when positions or timing deteriorate.",
    "Keep squats at 1–3 reps in reserve in most sessions.",
    "Add 2 kg total (1 kg per side) after all prescribed work is completed successfully. Automatic targets use whole kilograms. Misses, high RPE or limited recovery hold the load.",
    "Plan near-max attempts instead of taking them every session.",
    "Tuesday, Thursday and Sunday are recovery days; easy cycling, walking or mobility is fine if it does not impair lifting.",
  ],
  reviewCriteria: [
    "More stable snatches at your working loads",
    "Progress toward your own snatch goal",
    "Improved snatch balance strength and stability",
    "Improved power-clean and power-snatch numbers",
    "Repeatable, technically legal clean & jerks",
  ],
  days: [
    {
      id: "gym_accessories",
      weekday: null,
      name: "Any day",
      title: "Gym Accessories",
      focus:
        "Normal gym · rack, barbell and floor space · no platform or dropped lifts",
      sessionPrompt:
        "Warm up first and choose familiar, comfortable loads with 2–3 reps in reserve. Rest about 2 minutes between sets. Use rack safeties, lower every rep under control and follow the gym’s rules. This is an alternative session, not extra work you must add to the full week. Log total bar weight including the bar; for bodyweight movements enter 0 kg.",
      exercises: [
        {
          exerciseId: "romanian_deadlift",
          sets: 3,
          reps: "8",
          defaultReps: 8,
          initialWeight: "",
          progression: { step: 2 },
          recommendation: "Choose a comfortable starting weight",
          notes:
            "Start and finish from the rack. Keep the bar close, lower under control and do not drop it. Record total bar weight.",
          priority: 1,
          videoRef: "romanian_deadlift",
        },
        {
          exerciseId: "strict_press",
          sets: 3,
          reps: "8",
          defaultReps: 8,
          initialWeight: "",
          progression: { step: 2 },
          recommendation: "Choose a comfortable starting weight",
          notes:
            "Press from the rack without leg drive. Use a lighter bar if needed and leave 2–3 reps in reserve. No jerks or dropped bars.",
          priority: 2,
          videoRef: "strict_press",
        },
        {
          exerciseId: "barbell_row",
          sets: 3,
          reps: "10",
          defaultReps: 10,
          initialWeight: "",
          progression: { step: 2 },
          recommendation: "Choose a comfortable starting weight",
          notes:
            "Start from the rack, hinge to row and avoid heaving. Lower every rep under control. Record total bar weight.",
          priority: 3,
          videoRef: "barbell_row",
        },
        {
          exerciseId: "split_squat",
          sets: 3,
          reps: "16 total · 8 per leg",
          defaultReps: 16,
          initialWeight: "",
          progression: { step: 2 },
          recommendation: "Bodyweight or a comfortable added load",
          notes:
            "One logged set is 8 reps per leg: enter 16 total reps. Enter 0 kg for bodyweight, otherwise total added weight. Use rack safeties with a barbell; bodyweight sessions stay at 0 until you choose a loaded baseline.",
          priority: 4,
          videoRef: "split_squat",
        },
        {
          exerciseId: "dead_bug",
          sets: 3,
          reps: "16 total · 8 per side",
          defaultReps: 16,
          initialWeight: 0,
          recommendation: "Bodyweight · 0 kg",
          notes:
            "Alternate sides slowly. One logged set is 8 per side: enter 16 total reps and 0 kg. No automatic weight increases.",
          priority: 5,
          videoRef: "dead_bug",
        },
      ],
    },
    {
      id: "monday",
      weekday: 1,
      name: "Monday",
      title: "Snatch + Back Squat",
      focus: "Receiving stability and foundational leg strength",
      exercises: [
        {
          exerciseId: "snatch",
          sets: { min: 5, max: 8, default: 6 },
          reps: "1–2",
          defaultReps: 1,
          recommendation: "70–85% of your snatch",
          initialWeight: "",
          progression: { step: 2 },
          notes:
            "Pause for 2 seconds in the receiving position on technical reps.",
          priority: 1,
          videoRef: "snatch",
        },
        {
          exerciseId: "snatch_pull",
          sets: 4,
          reps: "3",
          defaultReps: 3,
          recommendation: "90–105% of your snatch",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Maintain snatch positions and speed.",
          priority: 2,
          videoRef: "snatch_pull",
        },
        {
          exerciseId: "back_squat",
          sets: 4,
          reps: "4",
          defaultReps: 4,
          recommendation: "72–80% of your back squat",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Leave 1–3 reps in reserve.",
          priority: 3,
          videoRef: "back_squat",
        },
        {
          exerciseId: "upper_back",
          sets: { min: 3, max: 4, default: 3 },
          reps: "6–10",
          defaultReps: 8,
          recommendation: "Controlled, submaximal",
          initialWeight: "",
          notes: "Choose rows or pull-ups.",
          priority: 4,
          videoRef: null,
        },
        {
          exerciseId: "trunk",
          sets: 3,
          reps: "Controlled",
          defaultReps: 10,
          recommendation: "Moderate",
          initialWeight: "",
          notes: "Choose one trunk exercise and keep the quality high.",
          priority: 5,
          videoRef: null,
        },
      ],
    },
    {
      id: "wednesday",
      weekday: 3,
      name: "Wednesday",
      title: "Clean & Jerk + Front Squat",
      focus: "Decisive jerk lockout and clean-specific leg strength",
      exercises: [
        {
          exerciseId: "clean_and_jerk",
          sets: { min: 5, max: 7, default: 6 },
          reps: "1",
          defaultReps: 1,
          recommendation: "75–88% of your clean & jerk",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Create immediate, unmistakable elbow lockout and hold it.",
          priority: 1,
          videoRef: "clean_and_jerk",
        },
        {
          exerciseId: "pause_clean",
          sets: { min: 3, max: 4, default: 3 },
          reps: "1–2",
          defaultReps: 2,
          recommendation: "Moderate",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Use a pause clean or a clean + front squat complex.",
          priority: 2,
          videoRef: "clean",
        },
        {
          exerciseId: "front_squat",
          sets: 4,
          reps: "3",
          defaultReps: 3,
          recommendation: "Choose a controlled working load",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Stay upright; leave 1–3 reps in reserve.",
          priority: 3,
          videoRef: "front_squat",
        },
        {
          exerciseId: "push_press",
          sets: 4,
          reps: "4",
          defaultReps: 4,
          recommendation: "Build gradually from your own starting load",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Drive vertically and finish every rep with a hard lockout.",
          priority: 4,
          videoRef: "push_press",
        },
        {
          exerciseId: "triceps_upper_back",
          sets: 3,
          reps: "8–12",
          defaultReps: 10,
          recommendation: "Controlled, submaximal",
          initialWeight: "",
          notes: "Select one triceps or upper-back accessory.",
          priority: 5,
          videoRef: null,
        },
      ],
    },
    {
      id: "friday",
      weekday: 5,
      name: "Friday",
      title: "Power + Overhead Stability",
      focus: "Specific power and a stable overhead receiving position",
      exercises: [
        {
          exerciseId: "power_snatch",
          sets: 5,
          reps: "2",
          defaultReps: 2,
          recommendation: "Choose a crisp, controlled load",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Receive tall and connected; do not chase borderline depth.",
          priority: 1,
          videoRef: "power_snatch",
        },
        {
          exerciseId: "snatch_balance",
          sets: 4,
          reps: "2",
          defaultReps: 2,
          recommendation: "Choose a stable, controlled load",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Emphasize speed under the bar and a stable bottom position.",
          priority: 2,
          videoRef: "snatch_balance",
        },
        {
          exerciseId: "overhead_squat",
          sets: 3,
          reps: "3",
          defaultReps: 3,
          recommendation: "Moderate",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Pause for 3 seconds in the bottom of every rep.",
          priority: 3,
          videoRef: "overhead_squat",
        },
        {
          exerciseId: "power_clean",
          sets: 5,
          reps: "2",
          defaultReps: 2,
          recommendation: "Choose a crisp, controlled load",
          initialWeight: "",
          progression: { step: 2 },
          notes: "Keep each lift crisp and establish your own working load.",
          priority: 4,
          videoRef: "power_clean",
        },
        {
          exerciseId: "posterior_chain",
          sets: 3,
          reps: "5–8",
          defaultReps: 6,
          recommendation: "Optional · moderate",
          initialWeight: "",
          notes:
            "Skip this if it would interfere with Saturday's coached session.",
          priority: 5,
          videoRef: null,
          optional: true,
        },
      ],
    },
    {
      id: "saturday",
      weekday: 6,
      name: "Saturday",
      title: "Coached Session",
      focus: "Competition lifts, coach feedback and repeatable execution",
      exercises: [
        {
          exerciseId: "snatch",
          sets: { min: 1, max: 10, default: 5 },
          reps: "Coach determines",
          defaultReps: 1,
          recommendation: "Coach determines intensity",
          initialWeight: "",
          notes: "Focus on receiving position, stability and repeatability.",
          priority: 1,
          videoRef: "snatch",
        },
        {
          exerciseId: "clean_and_jerk",
          sets: { min: 1, max: 10, default: 5 },
          reps: "Coach determines",
          defaultReps: 1,
          recommendation: "Coach determines intensity",
          initialWeight: "",
          notes: "Focus on a legal, decisive jerk lockout.",
          priority: 2,
          videoRef: "clean_and_jerk",
        },
      ],
      sessionPrompt:
        "Record only 1–2 actionable cues from your coach. Keep athlete observations and coach cues separate.",
    },
  ],
});
