import type { callModel } from "../agent/provider";
import type { refineVideo } from "./processor";
import { mergeSegmentation } from "./segmentation";
import { mergeBody } from "./body";
import type { VideoAnalysis, VideoUpload } from "./types";
import {
  VIDEO_REVIEW_VERSION,
  coachingText,
  type GuidedCoaching,
} from "./coaching";
import {
  attemptMessages,
  identifyAttempts,
  type VideoAttempt,
} from "./attempts";
import {
  identificationMessages,
  identifyLift,
  identificationSummary,
  respectSelectedLift,
  canReviewIdentification,
} from "./identification";
import { reviewMessages, reviewWithRecovery } from "./review";
import type { VideoRefinementCheckpoint } from "./checkpoint";

// Splits a clip into attempts, then refines and reviews each attempt in turn,
// checkpointing after every step so a restarted job resumes where it stopped.
export async function automaticFeedback(
  input: VideoUpload,
  initial: VideoAnalysis,
  frames: string[],
  model: typeof callModel,
  signal: AbortSignal,
  checkpoint: (
    analysis: VideoAnalysis,
    stage: string,
    clearRefinement?: boolean,
  ) => Promise<void>,
  refine: (
    analysis: VideoAnalysis,
    attempt: VideoAttempt,
  ) => Promise<
    Awaited<ReturnType<typeof refineVideo>> & {
      reviewed?: VideoRefinementCheckpoint["reviewed"];
      prepareBody: (
        reviewed: NonNullable<VideoRefinementCheckpoint["reviewed"]>,
      ) => Promise<VideoAnalysis["body"]>;
    }
  >,
  previous: (lift: string | null) => GuidedCoaching["previousFocus"],
) {
  // Resume only checkpoints generated by this pipeline. Saved older reviews
  // remain untouched until the owner explicitly requests reanalysis.
  let analysis =
    initial.reviewVersion === VIDEO_REVIEW_VERSION
      ? initial
      : {
          ...initial,
          reviewVersion: VIDEO_REVIEW_VERSION,
          attempts: undefined,
          coaching: undefined,
          identification: undefined,
        };
  if (!analysis.attempts) {
    const response = await model(
      input.mode === "automatic"
        ? attemptMessages(analysis, frames)
        : identificationMessages(analysis, frames),
      [],
      signal,
      undefined,
      { purpose: "video_review" },
    );
    signal.throwIfAborted();
    analysis = {
      ...analysis,
      attempts:
        input.mode === "automatic"
          ? identifyAttempts(
              response.tool_calls?.length ? "" : response.content,
              analysis,
              input.lift,
            )
          : [
              {
                id: "attempt-1",
                start: 0,
                end: analysis.duration,
                identification: respectSelectedLift(
                  identifyLift(
                    response.tool_calls?.length ? "" : response.content,
                    analysis,
                  ),
                  input.lift,
                ),
              },
            ],
    };
    await checkpoint(analysis, "Coach is reviewing your lift");
  }
  for (const attempt of analysis.attempts!) {
    if (!canReviewIdentification(attempt.identification) || attempt.coaching)
      continue;
    await checkpoint(
      analysis,
      `Reviewing ${attempt.identification.lift ?? "the visible movement"}`,
    );
    const refined = await refine(analysis, attempt);
    signal.throwIfAborted();
    const current = refined.analysis;
    if (current.segmentation) {
      analysis.segmentation = mergeSegmentation(
        analysis.segmentation,
        current.segmentation,
        attempt.start,
        attempt.end,
      );
    }
    if (current.pose?.version === 2) {
      const previous = analysis.pose?.version === 2 ? analysis.pose.frames : [];
      const merged = new Map(previous.map((f) => [f.t, f]));
      for (const frame of current.pose.frames)
        if (frame.t >= attempt.start && frame.t <= attempt.end)
          merged.set(frame.t, frame);
      // A failed exact-frame track must erase any older marker at that time.
      // Otherwise a new review could display a stale, plausible-looking point.
      for (const t of current.sampleTimes)
        merged.set(t, {
          t,
          points:
            current.pose.frames.find((f) => Math.abs(f.t - t) < 0.00001)
              ?.points ?? [],
        });
      analysis.pose = {
        ...current.pose,
        frames: [...merged.values()].sort((a, b) => a.t - b.t),
      };
    }
    if (current.tracking.source === "automatic_plate") {
      const points = [
        ...analysis.tracking.points.filter(
          (p) => p.t < attempt.start || p.t > attempt.end,
        ),
        ...current.tracking.points
          .filter((p) => p.t >= attempt.start && p.t <= attempt.end)
          .map((p) => ({ ...p, segment: attempt.id })),
      ].sort((a, b) => a.t - b.t);
      analysis.tracking = {
        ...current.tracking,
        points,
        status: points.length ? "partial" : "unavailable",
      };
    }
    analysis.overlayVersion = 1;
    await checkpoint(analysis, "Coach is reviewing the tracked movement");
    const focus = previous(attempt.identification.lift);
    const messages = reviewMessages(input, current, refined.frames, focus);
    messages[1].content = JSON.stringify({
      ...JSON.parse(messages[1].content),
      attempt: { start: attempt.start, end: attempt.end },
      instruction:
        "Review only this attempt. Every evidence frame must be within its start/end range. Other attempts are context only.",
    });
    const reviewed =
      refined.reviewed?.coaching && refined.reviewed.identification
        ? {
            coaching: refined.reviewed.coaching,
            identification: refined.reviewed.identification,
          }
        : await reviewWithRecovery(
            messages,
            current,
            input,
            attempt,
            model,
            signal,
            () =>
              checkpoint(analysis, "Checking Coach’s feedback automatically"),
          );
    const coaching = reviewed.coaching;
    if (focus && reviewed.identification.lift === attempt.identification.lift)
      coaching.previousFocus = focus;
    const body = await refined.prepareBody(reviewed);
    signal.throwIfAborted();
    if (body)
      analysis.body = mergeBody(
        analysis.body,
        body,
        attempt.start,
        attempt.end,
      );
    attempt.identification = reviewed.identification;
    attempt.coaching = coaching;
    await checkpoint(analysis, "Preparing your guided replay", true);
  }
  return summarizeAttempts(analysis, input);
}

// Combines each reviewed attempt into one review and one feedback text.
export function summarizeAttempts(initial: VideoAnalysis, input: VideoUpload) {
  let analysis = initial;
  const attempts = analysis.attempts!;
  const label = (i: number) =>
    attempts.length > 1
      ? `Attempt ${i + 1} · ${attempts[i].identification.lift ?? "Visible movement"}`
      : "";
  analysis = {
    ...analysis,
    reviewVersion: VIDEO_REVIEW_VERSION,
    overlayVersion: 1,
    identification: attempts[0].identification,
    coaching: {
      version: 2,
      checks: attempts.flatMap((a) => a.coaching?.checks ?? []),
      previousFocus: attempts.find((a) => a.coaching?.previousFocus)?.coaching
        ?.previousFocus,
      ...(attempts.some((a) => a.coaching?.scope === "visible_phases")
        ? { scope: "visible_phases" as const }
        : {}),
      strength: attempts
        .map((a, i) =>
          a.coaching?.strength
            ? [label(i), a.coaching.strength].filter(Boolean).join(": ")
            : "",
        )
        .filter(Boolean)
        .join("\n"),
      limitation: attempts
        .map((a, i) => {
          const text =
            a.coaching?.limitation ||
            (!a.identification.lift ? a.identification.reason : "");
          return text ? [label(i), text].filter(Boolean).join(": ") : "";
        })
        .filter(Boolean)
        .join("\n"),
      moments: attempts.flatMap((a, i) =>
        (a.coaching?.moments ?? []).map((m) => ({
          ...m,
          id: `${a.id}-${m.id}`,
          attemptLabel: label(i),
          start: Math.max(m.start, a.start),
          end: Math.min(m.end, a.end),
        })),
      ),
    },
  };
  return {
    analysis,
    feedback: attempts
      .map((a) =>
        [
          identificationSummary(a.identification, input.lift),
          a.coaching ? coachingText(a.coaching) : "",
        ]
          .filter(Boolean)
          .join("\n\n"),
      )
      .join("\n\n---\n\n"),
  };
}
