import { randomUUID } from "node:crypto";
import { and, eq } from "drizzle-orm";
import { getDb, getPool } from "../db";
import { liftingVideos, user } from "../db/schema";
import { callModel, ProviderError } from "../agent/provider";
import { ApiError } from "../agent/http";
import { userAllowed } from "../access";
import { processVideo, refineVideo } from "./processor";
import {
  sam3ConfigurationForAccount,
  segmentVideo,
  SegmentationPending,
  type Sam3Configuration,
} from "./sam3";
import { mergeSegmentation } from "./segmentation";
import { listVideos } from "./store";
import { previousVideoFocus } from "./focus";
import { MAX_VIDEO_BYTES, type VideoAnalysis, type VideoUpload } from "./types";
import { VIDEO_REVIEW_VERSION, coachingText } from "./coaching";
import { attemptMessages, identifyAttempts } from "./attempts";
import {
  identificationMessages,
  identifyLift,
  identificationSummary,
  respectSelectedLift,
  canReviewIdentification,
} from "./identification";
import {
  reviewMessages,
  reviewWithRecovery,
  ReviewValidationError,
} from "./review";
import {
  VIDEO_REFINEMENT_VERSION,
  type VideoRefinementCheckpoint,
} from "./checkpoint";
export { reviewMessages } from "./review";
async function automaticFeedback(
  input: VideoUpload,
  initial: VideoAnalysis,
  frames: string[],
  model: typeof callModel,
  signal: AbortSignal,
  checkpoint: (
    analysis: VideoAnalysis,
    stage: string,
    clearRefinement?: boolean,
  ) => Promise<void>,
  refine: (
    analysis: VideoAnalysis,
    attempt: import("./attempts").VideoAttempt,
  ) => ReturnType<typeof refineVideo>,
  previous: (
    lift: string | null,
  ) => import("./coaching").GuidedCoaching["previousFocus"],
) {
  // Resume only checkpoints generated by this pipeline. Saved older reviews
  // remain untouched until the owner explicitly requests reanalysis.
  let analysis =
    initial.reviewVersion === VIDEO_REVIEW_VERSION
      ? initial
      : {
          ...initial,
          reviewVersion: VIDEO_REVIEW_VERSION,
          attempts: undefined,
          coaching: undefined,
          identification: undefined,
        };
  if (!analysis.attempts) {
    const response = await model(
      input.mode === "automatic"
        ? attemptMessages(analysis, frames)
        : identificationMessages(analysis, frames),
      [],
      signal,
      undefined,
      { purpose: "video_review" },
    );
    signal.throwIfAborted();
    analysis = {
      ...analysis,
      attempts:
        input.mode === "automatic"
          ? identifyAttempts(
              response.tool_calls?.length ? "" : response.content,
              analysis,
              input.lift,
            )
          : [
              {
                id: "attempt-1",
                start: 0,
                end: analysis.duration,
                identification: respectSelectedLift(
                  identifyLift(
                    response.tool_calls?.length ? "" : response.content,
                    analysis,
                  ),
                  input.lift,
                ),
              },
            ],
    };
    await checkpoint(analysis, "Coach is reviewing your lift");
  }
  for (const attempt of analysis.attempts!) {
    if (!canReviewIdentification(attempt.identification) || attempt.coaching)
      continue;
    await checkpoint(
      analysis,
      `Reviewing ${attempt.identification.lift ?? "the visible movement"}`,
    );
    const refined = await refine(analysis, attempt);
    signal.throwIfAborted();
    const current = refined.analysis;
    if (current.segmentation) {
      analysis.segmentation = mergeSegmentation(
        analysis.segmentation,
        current.segmentation,
        attempt.start,
        attempt.end,
      );
    }
    if (current.pose?.version === 2) {
      const previous = analysis.pose?.version === 2 ? analysis.pose.frames : [];
      const merged = new Map(previous.map((f) => [f.t, f]));
      // A failed exact-frame track must erase any older marker at that time.
      // Otherwise a new review could display a stale, plausible-looking point.
      for (const t of current.sampleTimes)
        merged.set(t, {
          t,
          points:
            current.pose.frames.find((f) => Math.abs(f.t - t) < 0.00001)
              ?.points ?? [],
        });
      analysis.pose = {
        ...current.pose,
        frames: [...merged.values()].sort((a, b) => a.t - b.t),
      };
    }
    await checkpoint(analysis, "Coach is reviewing the tracked movement");
    const focus = previous(attempt.identification.lift);
    const messages = reviewMessages(input, current, refined.frames, focus);
    messages[1].content = JSON.stringify({
      ...JSON.parse(messages[1].content),
      attempt: { start: attempt.start, end: attempt.end },
      instruction:
        "Review only this attempt. Every evidence frame must be within its start/end range. Other attempts are context only.",
    });
    const reviewed = await reviewWithRecovery(
      messages,
      current,
      input,
      attempt,
      model,
      signal,
      () => checkpoint(analysis, "Checking Coach’s feedback automatically"),
    );
    const coaching = reviewed.coaching;
    if (focus && reviewed.identification.lift === attempt.identification.lift)
      coaching.previousFocus = focus;
    attempt.identification = reviewed.identification;
    attempt.coaching = coaching;
    await checkpoint(analysis, "Preparing your guided replay", true);
  }
  const attempts = analysis.attempts!;
  const label = (i: number) =>
    attempts.length > 1
      ? `Attempt ${i + 1} · ${attempts[i].identification.lift ?? "Visible movement"}`
      : "";
  analysis = {
    ...analysis,
    reviewVersion: VIDEO_REVIEW_VERSION,
    identification: attempts[0].identification,
    coaching: {
      version: 2,
      checks: attempts.flatMap((a) => a.coaching?.checks ?? []),
      previousFocus: attempts.find((a) => a.coaching?.previousFocus)?.coaching
        ?.previousFocus,
      ...(attempts.some((a) => a.coaching?.scope === "visible_phases")
        ? { scope: "visible_phases" as const }
        : {}),
      strength: attempts
        .map((a, i) =>
          a.coaching?.strength
            ? [label(i), a.coaching.strength].filter(Boolean).join(": ")
            : "",
        )
        .filter(Boolean)
        .join("\n"),
      limitation: attempts
        .map((a, i) => {
          const text =
            a.coaching?.limitation ||
            (!a.identification.lift ? a.identification.reason : "");
          return text ? [label(i), text].filter(Boolean).join(": ") : "";
        })
        .filter(Boolean)
        .join("\n"),
      moments: attempts.flatMap((a, i) =>
        (a.coaching?.moments ?? []).map((m) => ({
          ...m,
          id: `${a.id}-${m.id}`,
          attemptLabel: label(i),
          start: Math.max(m.start, a.start),
          end: Math.min(m.end, a.end),
        })),
      ),
    },
  };
  return {
    analysis,
    feedback: attempts
      .map((a) =>
        [
          identificationSummary(a.identification, input.lift),
          a.coaching ? coachingText(a.coaching) : "",
        ]
          .filter(Boolean)
          .join("\n\n"),
      )
      .join("\n\n---\n\n"),
  };
}

export async function claimVideo() {
  // Expired leases survive process restarts. A lease token fences every subsequent write.
  await getPool().query(
    "UPDATE lifting_videos SET status='failed',stage='Review interrupted',error='Processing was interrupted repeatedly. Retry this review.',lease=NULL WHERE status='processing' AND lease_until<now() AND attempts>=3",
  );
  const token = randomUUID();
  const { rows } = await getPool().query<{ user_id: string; id: string }>(
    `WITH next AS (
    SELECT user_id,id FROM lifting_videos WHERE ((status='queued' AND (lease_until IS NULL OR lease_until<=now())) OR (status='processing' AND lease_until<now())) AND attempts<3
    ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1)
    UPDATE lifting_videos v SET status='processing',stage='Preparing video',lease=$1,lease_until=now()+interval '11 minutes',attempts=attempts+1
    FROM next WHERE v.user_id=next.user_id AND v.id=next.id RETURNING v.user_id,v.id`,
    [token],
  );
  return rows[0] ? { ...rows[0], token } : null;
}
export async function runVideoJob(
  job: NonNullable<Awaited<ReturnType<typeof claimVideo>>>,
  model = callModel,
  processor = processVideo,
  refiner = refineVideo,
  segmenter = segmentVideo,
) {
  const fence = and(
    eq(liftingVideos.userId, job.user_id),
    eq(liftingVideos.id, job.id),
    eq(liftingVideos.lease, job.token),
  );
  let segmentationConfig: Sam3Configuration = {};
  const jobStarted = Date.now();
  const abort = new AbortController();
  const signal = AbortSignal.any([abort.signal, AbortSignal.timeout(600000)]);
  const check = async () => {
    const [account] = await getDb()
      .select()
      .from(user)
      .where(eq(user.id, job.user_id));
    const [exists] = await getDb()
      .select({ id: liftingVideos.id })
      .from(liftingVideos)
      .where(fence);
    if (!account || !exists || !(await userAllowed(account))) {
      abort.abort();
      return false;
    }
    segmentationConfig = sam3ConfigurationForAccount(account);
    return true;
  };
  const monitor = setInterval(() => {
    void check().catch(() => abort.abort());
  }, 10000);
  monitor.unref();
  try {
    if (!(await check())) return;
    const [row] = await getDb().select().from(liftingVideos).where(fence);
    let refinement =
      row.analysis?.reviewVersion === VIDEO_REVIEW_VERSION
        ? row.refinement
        : null;
    let analysis = row.analysis,
      frames = row.frames;
    let media = row.media;
    if (!analysis || !frames) {
      if (!row.source)
        throw new ApiError("This video is unavailable. Upload it again.", 422);
      const output = await processor(row.source, row.input, signal);
      signal.throwIfAborted();
      analysis = output.analysis;
      frames = output.frames;
      media = output.media;
      refinement = null;
      await getDb()
        .update(liftingVideos)
        .set({
          analysis,
          frames,
          refinement: null,
          media: output.media,
          source: null,
          bytes: MAX_VIDEO_BYTES,
          stage: "Identifying the movement phases",
        })
        .where(fence);
    }
    if (!(await check())) return;
    if (!media)
      throw new ApiError(
        "This video's playback is unavailable. Upload it again.",
        422,
      );
    // Each worker only waits briefly. A private receipt survives queue yields
    // and process restarts; the remote job has its own bounded lifetime.
    const segmentationBudget = {
      remainingMs: 90_000,
      deadlineMs: jobStarted + 480_000,
    };
    const priorReviews = await listVideos(row.userId);
    const result = await automaticFeedback(
      row.input,
      analysis,
      frames,
      model,
      signal,
      async (updated, stage, clearRefinement) => {
        if (!(await check())) signal.throwIfAborted();
        await getDb()
          .update(liftingVideos)
          .set({
            analysis: updated,
            stage,
            ...(clearRefinement ? { refinement: null } : {}),
          })
          .where(fence);
        if (clearRefinement) refinement = null;
      },
      async (current, attempt) => {
        if (!(await check())) signal.throwIfAborted();
        const reusable =
          refinement?.version === VIDEO_REFINEMENT_VERSION &&
          refinement.reviewVersion === VIDEO_REVIEW_VERSION &&
          current.reviewVersion === VIDEO_REVIEW_VERSION &&
          refinement.attemptId === attempt.id &&
          refinement.start === attempt.start &&
          refinement.end === attempt.end;
        let saved: VideoRefinementCheckpoint;
        if (reusable) saved = refinement!;
        else {
          const refined = await refiner(media!, current, attempt, signal);
          signal.throwIfAborted();
          saved = {
            version: VIDEO_REFINEMENT_VERSION,
            reviewVersion: VIDEO_REVIEW_VERSION,
            attemptId: attempt.id,
            start: attempt.start,
            end: attempt.end,
            sampleTimes: refined.analysis.sampleTimes,
            frames: refined.frames,
            pose: refined.analysis.pose,
            segmentation: refined.analysis.segmentation,
          };
          const bytes =
            media!.length +
            frames!.reduce((n, f) => n + f.length, 0) +
            Buffer.byteLength(JSON.stringify(current)) +
            Buffer.byteLength(JSON.stringify(saved));
          if (bytes > MAX_VIDEO_BYTES)
            throw new ApiError(
              "This review is too large. Try a shorter clip.",
              422,
            );
        }
        const save = async () => {
          if (!(await check())) signal.throwIfAborted();
          await getDb()
            .update(liftingVideos)
            .set({ refinement: saved })
            .where(fence);
          refinement = saved;
        };
        // Persist decoded evidence before dispatching any GPU work. A queued
        // receipt can then be resumed without decoding or uploading again.
        if (!reusable) await save();
        const detailed = {
          ...current,
          identification: attempt.identification,
          sampleTimes: saved.sampleTimes,
          pose: saved.pose,
          segmentation: saved.segmentation,
        };
        if (!saved.segmentation) {
          const segmentation = await segmenter(
            media!,
            detailed,
            signal,
            segmentationConfig,
            undefined,
            segmentationBudget,
            {
              job: saved.sam3Job,
              saveJob: async (job) => {
                saved = { ...saved, sam3Job: job };
                await save();
              },
            },
          );
          signal.throwIfAborted();
          saved = { ...saved, segmentation, sam3Job: undefined };
          await save();
          detailed.segmentation = segmentation;
        }
        return { analysis: detailed, frames: saved.frames };
      },
      (lift) =>
        previousVideoFocus(priorReviews, {
          id: row.id,
          createdAt: row.createdAt.toISOString(),
          lift,
        }),
    );
    analysis = result.analysis;
    const feedback = result.feedback;
    const bytes =
      (media?.length ?? 0) +
      frames.reduce((n, f) => n + f.length, 0) +
      Buffer.byteLength(JSON.stringify(analysis));
    if (bytes > MAX_VIDEO_BYTES)
      throw new ApiError("This review is too large. Try a shorter clip.", 422);
    await getDb()
      .update(liftingVideos)
      .set({
        status: "ready",
        bytes,
        stage: analysis.segmentation?.failure
          ? "Partial review · outlines unavailable"
          : analysis.coaching?.scope === "visible_phases"
            ? "Partial movement review"
            : "Review ready",
        analysis,
        feedback,
        refinement: null,
        error: null,
        lease: null,
        leaseUntil: null,
      })
      .where(fence);
  } catch (error) {
    if (error instanceof SegmentationPending && !signal.aborted) {
      const [saved] = await getDb().select().from(liftingVideos).where(fence);
      if (!saved || !(await check())) return;
      await getDb()
        .update(liftingVideos)
        .set({
          status: "queued",
          stage: "Preparing object outlines · continuing automatically",
          error: null,
          lease: null,
          leaseUntil: new Date(Date.now() + 15_000),
          // Waiting for the same GPU input is not a failed processing attempt.
          attempts: Math.max(0, saved.attempts - 1),
        })
        .where(fence);
      return;
    }
    console.warn(
      JSON.stringify({
        event: "video_job_failed",
        reason: signal.aborted
          ? "interrupted"
          : error instanceof ApiError
            ? "review_error"
            : "processing_or_provider_error",
      }),
    );
    const [saved] = await getDb().select().from(liftingVideos).where(fence);
    // A deleted/revoked account or superseded lease must never restart a job.
    if (!saved || !(await check())) return;
    const recoverable =
      error instanceof ReviewValidationError ||
      (error instanceof ProviderError &&
        (error.status === 429 || error.status >= 500)) ||
      (signal.aborted && !abort.signal.aborted);
    const retry = recoverable && saved.attempts < 3;
    // Save fixed diagnostic codes, never provider responses, inside the private
    // checkpoint so a deployment/log-retention boundary cannot erase the cause.
    await getDb()
      .update(liftingVideos)
      .set({
        status: retry ? "queued" : "failed",
        stage: retry
          ? "Finishing Coach’s feedback automatically"
          : "Feedback needs attention",
        error: retry
          ? null
          : error instanceof ApiError
            ? error.message
            : "Coach could not finish this review. Your saved video is safe; retry shortly.",
        lease: null,
        leaseUntil: retry
          ? new Date(Date.now() + 30_000 * saved.attempts)
          : null,
        ...(error instanceof ReviewValidationError && saved.refinement
          ? { refinement: { ...saved.refinement, failure: error.diagnostic } }
          : {}),
      })
      .where(fence);
  } finally {
    clearInterval(monitor);
  }
}
let started = false;
export function startVideoWorker() {
  if (
    started ||
    process.env.VIDEO_ANALYSIS_WORKER !== "1" ||
    !process.env.DATABASE_URL
  )
    return;
  started = true;
  const poll = async () => {
    try {
      const job = await claimVideo();
      if (job) await runVideoJob(job);
    } catch {
      console.error(JSON.stringify({ event: "video_worker_unavailable" }));
    }
    setTimeout(() => void poll(), 5000).unref();
  };
  void poll();
}
