import { z } from "zod";
import "./health-sync";
import { nativeRequests, nativeResponses } from "./native-api";

// Builds the OpenAPI document for the iPhone app from the zod schemas in
// native-api.ts (and the health sync request in health-sync.ts). The result is
// committed at ios/Packages/LiftKit/Sources/LiftAPI/openapi.json, where Swift
// OpenAPI Generator turns it into the app's client at build time; a test fails
// when the committed copy is stale.
//
// Responses are made tolerant for installed builds: no closed enums, no
// rejected extra fields, and timestamps as plain strings. The server can then
// add a field or an enum value without breaking an older app. Removing or
// renaming a field still breaks it, and needs MIN_IOS_BUILD raised.
type Json = { [key: string]: unknown };

const SAFE = 9007199254740991;
function loosen(node: unknown, response: boolean): unknown {
  if (Array.isArray(node)) return node.map((n) => loosen(n, response));
  if (!node || typeof node !== "object") return node;
  const source = node as Json;
  // A lone reference wrapped in allOf (zod's form for optional and nullable
  // references) becomes a plain reference; null is treated as absent below.
  const all = source.allOf as Json[] | undefined;
  if (all?.length === 1 && typeof all[0].$ref === "string")
    return { $ref: all[0].$ref };
  const out: Json = {};
  for (const [key, value] of Object.entries(source)) {
    if (key === "properties") {
      // Keys here are field names, not schema keywords.
      out.properties = Object.fromEntries(
        Object.entries(value as Json).map(([name, v]) => [
          name,
          loosen(v, response),
        ]),
      );
      continue;
    }
    if (key === "additionalProperties" && value === false) continue;
    if (key === "format" && value === "date-time") continue;
    if (["pattern", "$schema", "$id", "nullable"].includes(key)) continue;
    if (
      (key === "minimum" || key === "maximum") &&
      Math.abs(value as number) === SAFE
    )
      continue;
    // Nullable fields are optional: the generated client decodes null as absent.
    if (key === "required" && source.properties) {
      const props = source.properties as Record<string, Json>;
      const required = (value as string[]).filter(
        (name) => !props[name]?.nullable,
      );
      if (required.length) out.required = required;
      continue;
    }
    if (response && key === "enum") {
      out.description = [
        source.description,
        `One of: ${(value as unknown[]).join(", ")}. Treat others as unknown.`,
      ]
        .filter(Boolean)
        .join(" ");
      continue;
    }
    out[key] = loosen(value, response);
  }
  return out;
}

const schemas = (
  registry: typeof nativeResponses,
  io: "input" | "output",
): Json =>
  (
    z.toJSONSchema(registry, {
      target: "openapi-3.0",
      io,
      unrepresentable: "any",
      uri: (id) => `#/components/schemas/${id}`,
    }) as { schemas: Json }
  ).schemas;

const json = (ref: string) => ({
  content: {
    "application/json": { schema: { $ref: `#/components/schemas/${ref}` } },
  },
});
const ok = (ref: string, description = "OK") => ({
  "200": { description, ...json(ref) },
  default: { description: "Error", ...json("ErrorBody") },
});
const query = (name: string, required: boolean, type = "string") => ({
  name,
  in: "query",
  required,
  schema: { type },
});

export function buildOpenApi() {
  const responses = loosen(schemas(nativeResponses, "output"), true) as Json;
  const requests = loosen(schemas(nativeRequests, "input"), false) as Json;
  // Tag each action with its kind so the client decodes a proper Swift enum.
  const action = requests.NativeAction as Json;
  const refs = (action.oneOf ?? action.anyOf) as { $ref: string }[];
  delete action.anyOf;
  action.oneOf = refs;
  action.discriminator = {
    propertyName: "kind",
    mapping: Object.fromEntries(
      refs.map((r) => {
        const id = r.$ref.split("/").pop()!;
        const kind = ((requests[id] as Json).properties as Json).kind as Json;
        return [(kind.enum as string[])[0], r.$ref];
      }),
    ),
  };
  return {
    openapi: "3.0.3",
    info: {
      title: "Lift Journal iPhone API",
      version: "1",
      description:
        "Generated by lib/native-openapi.ts. Do not edit; run `npm run openapi`.",
    },
    servers: [{ url: "https://lift-journal-production.up.railway.app" }],
    security: [{ bearer: [] }],
    paths: {
      "/api/v1/config": {
        get: {
          operationId: "getConfig",
          security: [],
          responses: ok("NativeConfig"),
        },
      },
      "/api/session": {
        get: { operationId: "getSession", responses: ok("SessionInfo") },
      },
      "/api/mobile/token": {
        post: {
          operationId: "exchangeToken",
          security: [],
          requestBody: { required: true, ...json("TokenRequest") },
          responses: ok("TokenResponse"),
        },
      },
      "/api/v1/today": {
        get: {
          operationId: "getToday",
          parameters: [query("date", true)],
          responses: ok("Today"),
        },
      },
      "/api/v1/journal": {
        get: {
          operationId: "getJournal",
          parameters: [query("before", true), query("days", false, "integer")],
          responses: ok("JournalFeed"),
        },
      },
      "/api/v1/actions": {
        post: {
          operationId: "applyAction",
          requestBody: { required: true, ...json("ActionRequest") },
          responses: ok("ActionResult"),
        },
      },
      "/api/v1/health/sync": {
        post: {
          operationId: "syncHealth",
          requestBody: { required: true, ...json("HealthSyncRequest") },
          responses: ok("HealthSyncResult"),
        },
      },
      "/api/v1/coach": {
        get: { operationId: "getCoach", responses: ok("CoachHistory") },
      },
      "/api/agent/action": {
        post: {
          operationId: "applyProposal",
          requestBody: { required: true, ...json("ProposalRequest") },
          responses: {
            "200": { description: "OK" },
            default: { description: "Error", ...json("ErrorBody") },
          },
        },
      },
      "/api/images": {
        post: {
          operationId: "uploadImage",
          requestBody: { required: true, ...json("ImageUpload") },
          responses: {
            "200": { description: "OK" },
            default: { description: "Error", ...json("ErrorBody") },
          },
        },
      },
    },
    components: {
      securitySchemes: { bearer: { type: "http", scheme: "bearer" } },
      schemas: Object.fromEntries(
        Object.entries({ ...responses, ...requests }).sort(([a], [b]) =>
          a.localeCompare(b),
        ),
      ),
    },
  };
}

export const fixturesPath = "ios/Packages/LiftKit/Tests/LiftKitTests/Fixtures";
export const openApiPath = "ios/Packages/LiftKit/Sources/LiftAPI/openapi.json";
export const openApiText = () => `${JSON.stringify(buildOpenApi(), null, 2)}\n`;
